<a href="https://colab.research.google.com/github/see-3pO/fifa21-Data-Cleaning-Project/blob/master/fifa21_players_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction


This is a data cleaning and transformation project of fifa21 players dataset sourced from [here](https://www.kaggle.com/datasets/yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring?select=fifa21_raw_data.csv%E2%80%8B).
Some of the guiding questions I followed include:
*   Do the height and weight columns have the appropriate data types?
* Can you separate the joined columns into year, month, and day columns?
* Can you clean and transform the value, wage, and release clause columns into columns of integers?
* How can you remove the newline characters from the Club column
* Should you separate the Team & Contract Column into separate team and contract columns?

## Code

### 1.  Importing necessary libraries

In [ ]:
#mounting the google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#checking the current working directory
!pwd

/content

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

### 2. Creating the dataframe `fifa_df`  to be used

In [ ]:
fifa_df = pd.read_csv('/content/drive/MyDrive/Datasets/fifa21 raw data v2.csv')
fifa_df
fifa_df.head()

<ipython-input-102-ecfa1c025293>:1: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  fifa_df = pd.read_csv('/content/drive/MyDrive/Datasets/fifa21 raw data v2.csv')

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [ ]:
fifa_df.tail()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,\n\n\n\nWuhan Zall,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,\n\n\n\nOldham Athletic,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,\n\n\n\nDerry City,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

### 3. Understanding the data

In [ ]:
fifa_df.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [ ]:
fifa_df.shape

(18979, 77)

In [ ]:
fifa_df.isnull().sum()

ID              0
Name            0
LongName        0
photoUrl        0
playerUrl       0
             ...
PAS             0
DRI             0
DEF             0
PHY             0
Hits         2595
Length: 77, dtype: int64

In [ ]:
fifa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  object
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  object
dtypes: int64(54), object(23)
memory usage: 11.1+ MB

In [ ]:
fifa_df.describe()

,ID,Age,↓OVA,POT,BOV,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,...,GK Positioning,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY
count,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,...,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000
mean,226403.384794,25.194109,65.718636,71.136414,66.751726,248.938142,49.688392,45.842405,51.942726,58.768112,...,16.217187,16.519627,1595.286949,355.702197,67.453975,53.457031,57.681016,62.875020,49.866221,64.368934
std,27141.054157,4.710520,6.968999,6.114635,6.747193,74.299428,18.131153,19.567081,17.294409,14.519106,...,17.002239,17.854079,269.874789,40.761117,10.677859,13.827425,10.081857,9.927415,16.443213,9.601883
min,41.000000,16.000000,47.000000,47.000000,48.000000,42.000000,6.000000,3.000000,5.000000,7.000000,...,2.000000,2.000000,747.000000,232.000000,25.000000,16.000000,25.000000,25.000000,12.000000,28.000000
25%,210135.000000,21.000000,61.000000,67.000000,62.000000,222.000000,38.000000,30.000000,44.000000,54.000000,...,8.000000,8.000000,1452.000000,327.000000,61.000000,44.000000,51.000000,57.000000,35.000000,58.000000
50%,232418.000000,25.000000,66.000000,71.000000,67.000000,263.000000,54.000000,49.000000,55.000000,62.000000,...,11.000000,11.000000,1627.000000,356.000000,68.000000,56.000000,58.000000,64.000000,53.000000,65.000000
75%,246922.500000,29.000000,70.000000,75.000000,71.000000,297.000000,63.000000,62.000000,64.000000,68.000000,...,14.000000,14.000000,1781.000000,384.000000,75.000000,64.000000,64.000000,69.000000,63.000000,71.000000
max,259216.000000,53.000000,93.000000,95.000000,93.000000,437.000000,94.000000,95.000000,93.000000,94.000000,...,91.000000,90.000000,2316.000000,498.000000,96.000000,93.000000,93.000000,95.000000,91.000000,91.000000

In [ ]:
#Including only string columns in a DataFrame description.
fifa_df.describe(include=object)

,Name,LongName,photoUrl,playerUrl,Nationality,Club,Contract,Positions,Height,Weight,...,Loan Date End,Value,Wage,Release Clause,W/F,SM,A/W,D/W,IR,Hits
count,18979,18979,18979,18979,18979,18979,18979,18979,18979,18979,...,1013,18979,18979,18979,18979,18979,18979,18979,18979,16384
unique,17920,18852,18979,18979,164,682,131,640,62,79,...,24,255,134,1216,5,5,3,3,5,450
top,J. Rodríguez,Danny Rose,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,England,No Club,2019 ~ 2021,CB,180cm,70kg,...,"Jun 30, 2021",€1.2M,€2K,€0,3 ★,2★,Medium,Medium,1 ★,1
freq,13,3,1,1,1705,237,1706,2441,1474,1495,...,770,582,2899,1261,11695,9142,12701,13956,17629,2325

### 4. Cleaning the Data

#### 4.1 Dropping non-relevant columns

In [ ]:
fifa_df.drop(columns=['photoUrl','playerUrl','LongName','Nationality'], inplace=True)
fifa_df.head()

,ID,Name,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187cm,83kg,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188cm,87kg,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,...,High,Medium,5 ★,91,85,86,94,36,59,595

#### 4.2 Can you separate the joined columns into year, month, and day columns?

In [ ]:
fifa_df['Joined']

0         Jul 1, 2004
1        Jul 10, 2018
2        Jul 16, 2014
3        Aug 30, 2015
4         Aug 3, 2017
             ...
18974    Jul 13, 2018
18975     Aug 1, 2020
18976     Mar 8, 2019
18977    Sep 22, 2020
18978    Jul 29, 2019
Name: Joined, Length: 18979, dtype: object

In [ ]:
#making the dates into the right data type
#converting the months to corresponding number
def monthToNumber(x):
  if x == 'Jan':
    return 1
  elif x== 'Feb':
    return 2
  elif x== 'Mar':
    return 3
  elif x== 'Apr':
    return 4
  elif x== 'May':
    return 5
  elif x== 'Jun':
    return 6
  elif x== 'Jul':
    return 7
  elif x== 'Aug':
    return 8
  elif x== 'Sep':
    return 9
  elif x== 'Oct':
    return 10
  elif x== 'Nov':
    return 11
  elif x== 'Dec':
    return 12
  else:
    return "Error"

In [ ]:
# creating list called date_list to store the converted dates
date_list = []
# solitting the date and modifying the day, month, and year
for x in range(len(fifa_df["Joined"])):
  date = fifa_df["Joined"][x]
  split_date = date.split(" ")
  month = str(monthToNumber(split_date[0]))
  day = str(split_date[1].replace(',',''))
  year = str(split_date[2])

  #adding 0 to single digit dates
  if len(day) == 1:
    day = ('0'+str(day))
  #recombiing the split date and then converting to correct format
  full_date = (str(month)+'/'+str(day)+'/'+str(year))
  converted_date = pd.to_datetime(full_date)
  date_list.append(converted_date)

In [ ]:
fifa_df["Joined"] = date_list
fifa_df["Joined"]

0       2004-07-01
1       2018-07-10
2       2014-07-16
3       2015-08-30
4       2017-08-03
           ...
18974   2018-07-13
18975   2020-08-01
18976   2019-03-08
18977   2020-09-22
18978   2019-07-29
Name: Joined, Length: 18979, dtype: datetime64[ns]

In [ ]:
type(fifa_df["Joined"])

pandas.core.series.Series

In [ ]:
fifa_df['Day'] = fifa_df["Joined"].dt.day
fifa_df['Month'] = fifa_df["Joined"].dt.month
fifa_df['Year'] = fifa_df["Joined"].dt.year
fifa_df.head()

,ID,Name,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,...,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Day,Month,Year
0,158023,L. Messi,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,...,85,92,91,95,38,65,771,1,7,2004
1,20801,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187cm,83kg,...,89,93,81,89,35,77,562,10,7,2018
2,200389,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188cm,87kg,...,87,92,78,90,52,90,150,16,7,2014
3,192985,K. De Bruyne,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,...,76,86,93,88,64,78,207,30,8,2015
4,190871,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,...,91,85,86,94,36,59,595,3,8,2017

In [ ]:
fifa_df.columns

Index(['ID', 'Name', 'Age', '↓OVA', 'POT', 'Club', 'Contract', 'Positions',
       'Height', 'Weight', 'Preferred Foot', 'BOV', 'Best Position', 'Joined',
       'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Attacking',
       'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility',
       'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina',
       'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions',
       'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W',
       'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits', 'Day', 'Month',
       'Year'],
      dtype='object')

In [ ]:
fifa_df.drop("Joined", axis=1, inplace=True)

#### 4.3 How can you remove the newline characters from the `Club` column

In [ ]:
fifa_df['Club'] = fifa_df['Club'].str.replace('\n\n\n\n','')
fifa_df.head()

,ID,Name,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,...,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Day,Month,Year
0,158023,L. Messi,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,...,85,92,91,95,38,65,771,1,7,2004
1,20801,Cristiano Ronaldo,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187cm,83kg,...,89,93,81,89,35,77,562,10,7,2018
2,200389,J. Oblak,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188cm,87kg,...,87,92,78,90,52,90,150,16,7,2014
3,192985,K. De Bruyne,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,...,76,86,93,88,64,78,207,30,8,2015
4,190871,Neymar Jr,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,...,91,85,86,94,36,59,595,3,8,2017

In [ ]:
fifa_df.Club.unique()

array(['FC Barcelona', 'Juventus', 'Atlético Madrid', 'Manchester City',
       'Paris Saint-Germain', 'FC Bayern München', 'Liverpool',
       'Real Madrid', 'Chelsea', 'Tottenham Hotspur', 'Inter', 'Napoli',
       'Borussia Dortmund', 'Manchester United', 'Arsenal', 'Lazio',
       'Leicester City', 'Borussia Mönchengladbach', 'Real Sociedad',
       'Atalanta', 'Olympique Lyonnais', 'Milan', 'Villarreal CF',
       'RB Leipzig', 'Cagliari', 'Ajax', 'SL Benfica', 'AS Monaco',
       'Wolverhampton Wanderers', 'Everton', 'Fiorentina', 'FC Porto',
       'RC Celta', 'Torino', 'Sevilla FC', 'Grêmio', 'Real Betis', 'Roma',
       'Newcastle United', 'Eintracht Frankfurt', 'Valencia CF',
       'Medipol Başakşehir FK', 'Inter Miami', 'Bayer 04 Leverkusen',
       'Levante UD', 'Crystal Palace', 'Athletic Club de Bilbao',
       'Shanghai SIPG FC', 'VfL Wolfsburg',
       'Guangzhou Evergrande Taobao FC', 'Al Shabab',
       'Olympique de Marseille', 'Los Angeles FC',
       'Beijing Sinobo Guoan FC', 'Getafe CF', 'SV Werder Bremen',
       'TSG 1899 Hoffenheim', 'LOSC Lille', 'Deportivo Alavés', 'Burnley',
       'Leeds United', 'Fulham', 'PFC CSKA Moscow', 'Genoa',
       'Galatasaray SK', 'Atlanta United', 'Atlético Mineiro', 'Flamengo',
       'Palmeiras', 'No Club', 'São Paulo', 'West Ham United', 'SD Eibar',
       'River Plate', 'OGC Nice', 'Real Valladolid CF', 'Sporting CP',
       'PSV', 'Feyenoord', 'Club Brugge KV', 'Shakhtar Donetsk',
       'Vissel Kobe', 'Boca Juniors', '1. FC Union Berlin',
       'Dalian YiFang FC', 'AS Saint-Étienne', 'Sassuolo',
       'Tigres U.A.N.L.', 'Dinamo Zagreb', 'Dynamo Kyiv', 'Fluminense',
       'Udinese', 'Aston Villa', 'Stade Rennais FC', 'Beşiktaş JK',
       'Brighton & Hove Albion', 'Hebei China Fortune FC', 'Southampton',
       'Lokomotiv Moscow', 'Jiangsu Suning FC', 'Al Hilal',
       'West Bromwich Albion', 'Fenerbahçe SK', 'FC Groningen',
       'Guangzhou R&F FC', 'Orlando City SC', 'Sampdoria',
       'Stade de Reims', 'Sheffield United', 'Santos', 'Internacional',
       'Coritiba', 'CA Osasuna', 'LA Galaxy', 'Al Nassr', 'SC Freiburg',
       'SC Braga', 'Olympiacos CFP', 'Toronto FC', 'Granada CF',
       'FC Schalke 04', 'RC Strasbourg Alsace', 'Hertha BSC',
       'AZ Alkmaar', 'Seattle Sounders FC', 'Montpellier HSC',
       'Shanghai Greenland Shenhua FC', 'Hamburger SV', 'Girona FC',
       'Racing Club', 'Portland Timbers', 'FC Girondins de Bordeaux',
       'Watford', 'Estudiantes de La Plata', 'Club América',
       'Vitória Guimarães', 'SK Slavia Praha', 'Trabzonspor',
       'RCD Espanyol', 'FC Nantes', 'Angers SCO', 'Cruz Azul',
       'BSC Young Boys', 'Club León', 'Spartak Moscow', 'Sivasspor',
       'Elche CF', 'FC Augsburg', 'Wuhan Zall', 'Parma',
       'Royal Antwerp FC', 'Monterrey', 'San Lorenzo de Almagro',
       'AC Monza', 'Club Atlético Lanús', 'SD Huesca', 'Derby County',
       'Kayserispor', 'RSC Anderlecht', 'CD Leganés', 'Vélez Sarsfield',
       'Stade Brestois 29', 'Tianjin TEDA FC', 'Birmingham City',
       'Hellas Verona', '1. FC Köln', 'Al Wehda', 'Bournemouth',
       'Alanyaspor', 'Bologna', 'Amiens SC', 'Celtic',
       'Shijiazhuang Ever Bright F.C.', 'Club Atlas', 'Al Ahli',
       'Norwich City', 'Fatih Karagümrük S.K.', 'Club Tijuana',
       'Universidad Católica', 'Goiás', 'Benevento', 'Independiente',
       'Qingdao Huanghai F.C.', 'Brentford', 'AEK Athens',
       'Racing Club de Lens', 'Olimpia Asunción', 'Shenzhen FC',
       'Çaykur Rizespor', 'KAA Gent', 'New England Revolution',
       'Cádiz CF', '1. FSV Mainz 05', 'Vasco da Gama', 'FC Midtjylland',
       'Al Ain FC', 'Santos Laguna', 'SPAL', 'Perth Glory', 'FC Utrecht',
       'Montreal Impact', 'UD Almería', 'Fortaleza', 'Spezia',
       'FC Basel 1893', 'FC København', 'Godoy Cruz', 'Deportivo Toluca',
       'Nacional de Montevideo', 'Aalborg BK', 'Rio Ave FC', 'FC Metz',
       'Chongqing Dangdai Lifan FC SWM Team', 'Rosenborg BK',
       'FC Red Bull Salzburg', 'Botafogo', 'DSC Arminia Bielefeld',
       'Club Athletico Paranaense', 'RCD Mallorca', 'Pachuca',
       'Swansea City', 'KRC Genk', 'En Avant de Guingamp', 'Lecce',
       'Nîmes Olympique', 'Colo-Colo', 'Stade Malherbe Caen',
       'Columbus Crew SC', 'Junior FC', 'VfB Stuttgart', 'Moreirense FC',
       'Rangers FC', 'Malmö FF', 'Shandong Luneng TaiShan FC',
       'Sparta Praha', 'Hatayspor', 'Chicago Fire',
       'Toulouse Football Club', 'FC Seoul', 'Antalyaspor',
       'Deportivo Cali', 'Kaizer Chiefs', 'Real Zaragoza',
       'Atlético Clube Goianiense', 'Puebla FC', 'Fortuna Düsseldorf',
       'Western United FC', 'Astra Giurgiu', 'Henan Jianye FC', 'Bahia',
       'Famalicão', 'Atiker Konyaspor', 'Peñarol', 'DC United',
       'New York City FC', 'Argentinos Juniors', 'U.N.A.M.',
       'Minnesota United FC', 'Nottingham Forest',
       'Independiente del Valle', 'Defensa y Justicia',
       'Philadelphia Union', "Newell's Old Boys", 'Rosario Central',
       'Atlético de San Luis', 'FC Dallas', 'Denizlispor',
       'Yeni Malatyaspor', 'Club Atlético Colón', 'Houston Dynamo',
       'Millwall', 'Clube Sport Marítimo', 'MKE Ankaragücü',
       'Guadalajara', 'Boavista FC', 'Sporting Kansas City',
       'Atlético Nacional', 'CD Lugo', 'New York Red Bulls', 'PAOK',
       'SC Heerenveen', 'Daegu FC', 'Preston North End', 'Damac FC',
       'Brescia', 'VfL Bochum 1848', 'Vancouver Whitecaps FC',
       'SV Sandhausen', 'Royal Excel Mouscron', 'Dijon FCO', 'Molde FK',
       'Panathinaikos FC', 'LASK Linz', 'Ulsan Hyundai FC',
       'Real Salt Lake', 'FC Luzern', 'Viktoria Plzeň', 'Orlando Pirates',
       'Al Ittihad', '1. FC Nürnberg', 'Standard de Liège',
       'Rayo Vallecano', 'Club Libertad', 'Jeonbuk Hyundai Motors',
       'Western Sydney Wanderers', 'Unión de Santa Fe', 'FC Sion',
       'Sydney FC', 'Hannover 96', 'Real Sporting de Gijón',
       'FC Cincinnati', 'ESTAC Troyes', 'San Jose Earthquakes',
       'Club Guaraní', 'FC Lorient', 'Gençlerbirliği SK',
       'Sporting de Charleroi', 'Wisła Kraków', 'Al Taawoun', 'Reading',
       'Gazişehir Gaziantep F.K.', 'Blackburn Rovers', 'Kashiwa Reysol',
       'FK Bodø/Glimt', 'Willem II', 'Vitesse', 'Gil Vicente FC',
       'SønderjyskE', 'Yokohama F. Marinos', 'FC St. Gallen',
       'Club Atlético Aldosivi', 'Göztepe SK', 'Holstein Kiel',
       'FC Juárez', 'FCSB (Steaua)', 'Ettifaq FC', 'KAS Eupen',
       'FC Tokyo', 'Melbourne City FC', 'Universitatea Craiova',
       'CD Tondela', 'Wolfsberger AC', 'Ceará Sporting Club',
       'River Plate Asunción', 'Stoke City', 'Paris FC', 'IFK Norrköping',
       'Crotone', 'Cardiff City', 'América de Cali', 'Al Faisaly',
       'Independiente Medellín', 'Portimonense SC', 'CD Tenerife',
       'Heracles Almelo', 'Nashville SC', 'SK Rapid Wien',
       'Kawasaki Frontale', 'Club Necaxa', 'Chievo Verona', 'Lech Poznań',
       'AIK', 'FK Austria Wien', 'Querétaro', '1. FC Heidenheim 1846',
       'Legia Warszawa', 'Club Atlético Banfield', 'Os Belenenses',
       'Huddersfield Town', 'KSV Cercle Brugge', 'LDU Quito',
       'Gimnasia y Esgrima La Plata', 'Gamba Osaka', 'Middlesbrough',
       'Servette FC', 'Empoli', 'Real Oviedo', 'Kasimpaşa SK', 'CFR Cluj',
       'Millonarios FC', 'FC Paços de Ferreira', 'Sint-Truidense VV',
       'AD Alcorcón', 'Colorado Rapids', 'Dinamo Bucureşti',
       'Cerezo Osaka', 'FC Emmen', 'Sheffield Wednesday',
       'FC Erzgebirge Aue', 'Raków Częstochowa', 'Atlético Tucumán',
       'SV Darmstadt 98', 'Bristol City', 'Oud-Heverlee Leuven',
       'Barnsley', 'Queens Park Rangers', 'Sangju Sangmu FC',
       'Helsingborgs IF', 'AC Ajaccio', 'Oceânico FC',
       'Club Atlético Talleres', 'Al Hazem', 'SC Paderborn 07',
       'Club Atlético Huracán', 'KV Kortrijk', 'El Nacional',
       'Mazatlán FC', 'Aberdeen', 'CD Mirandés', 'SV Zulte-Waregem',
       'Piast Gliwice', 'Djurgårdens IF', 'Central Córdoba',
       'Wellington Phoenix', 'Deportivo Binacional', 'Patronato',
       'SpVgg Greuther Fürth', 'IFK Göteborg', 'FC Cartagena',
       'Santa Clara', 'FC Twente', 'Farense', 'ADO Den Haag',
       'AJ Auxerre', 'Al Fateh', 'Valenciennes FC',
       'Hokkaido Consadole Sapporo', 'FC St. Pauli', 'Albacete BP',
       '1. FC Kaiserslautern', 'Al Fayha', 'Incheon United FC',
       'KV Mechelen', 'Pohang Steelers', 'CD Nacional', 'Unión La Calera',
       'BB Erzurumspor', 'Kashima Antlers', 'Arsenal de Sarandí',
       'HJK Helsinki', 'Karlsruher SC', 'Aarhus GF', 'FC Zürich',
       'Barcelona Sporting Club', 'SG Dynamo Dresden',
       'Sanfrecce Hiroshima', 'Al Raed', 'SD Ponferradina', 'Brøndby IF',
       'Lechia Gdańsk', 'FC Viitorul', 'SK Sturm Graz', 'IF Elfsborg',
       'Gangwon FC', 'Melgar FBC', 'Club Atlético Grau',
       'Jagiellonia Białystok', 'Waasland-Beveren', 'VfL Osnabrück',
       'Nagoya Grampus', 'CF Fuenlabrada', 'Shamrock Rovers',
       'Shimizu S-Pulse', 'RKC Waalwijk', 'Vålerenga Fotball',
       'Clermont Foot 63', 'FC Ingolstadt 04', 'FC Würzburger Kickers',
       'Górnik Zabrze', 'Charlton Athletic', 'Beerschot AC',
       'Coquimbo Unido', 'Viktoria Köln', 'Hull City', 'Málaga CF',
       'FC Nordsjælland', 'UD Las Palmas', 'VVV-Venlo', 'GwangJu FC',
       'Chamois Niortais Football Club', 'FC Lugano', 'Cusco FC',
       'Sparta Rotterdam', 'Sol de América', 'PEC Zwolle',
       'Pogoń Szczecin', 'Doncaster Rovers', 'Kristiansund BK',
       'Liverpool Fútbol Club', 'Club Bolívar', 'Urawa Red Diamonds',
       'SK Brann', 'Eintracht Braunschweig', 'Nacional Asunción',
       'Melbourne Victory', 'Kilmarnock', 'Dundalk',
       'SSV Jahn Regensburg', 'Abha Club', 'Club Atlético Tigre',
       'Suwon Samsung Bluewings', 'Shonan Bellmare', 'SD Aucas', 'Emelec',
       'Fortuna Sittard', 'La Berrichonne de Châteauroux',
       'Śląsk Wrocław', 'Coventry City', 'Sunderland', 'Alianza Lima',
       'Hammarby IF', 'Cracovia', 'CE Sabadell FC', 'Oita Trinita',
       'BK Häcken', 'Luton Town', 'Le Havre AC', 'IK Sirius',
       'Zagłębie Lubin', 'Grenoble Foot 38', 'Macarthur FC',
       'Rodez Aveyron Football', 'Vegalta Sendai', 'Motherwell',
       'SV Wehen Wiesbaden', 'Audax Italiano', 'Gaz Metan Mediaş',
       'Portsmouth', 'Hibernian', 'Always Ready', 'UD Logroñés',
       'FC Voluntari', 'FC Hermannstadt', 'AS Nancy Lorraine',
       'Rotherham United', 'Fleetwood Town', 'Jorge Wilstermann',
       'Odense Boldklub', 'MSV Duisburg', 'FC Sochaux-Montbéliard',
       'Milton Keynes Dons', 'River Plate Montevideo', 'Delfín SC',
       'Universidad Católica del Ecuador', 'Deportivo Pasto',
       'KV Oostende', 'Club Plaza Colonia', 'Wigan Athletic',
       'FC Botoşani', 'C.D. Castellón', 'SCR Altach', 'Örebro SK',
       'TSV Hartberg', 'Stabæk Fotball', 'Wycombe Wanderers',
       'St. Johnstone FC', 'Oxford United', 'Lincoln City', 'Randers FC',
       'Viking FK', 'FC Chambly Oise', 'Dundee United',
       'Oriente Petrolero', 'Odds BK', 'Nacional Potosí', 'Sepsi OSK',
       'FC Hansa Rostock', 'Lyngby BK', 'SpVgg Unterhaching',
       'Brisbane Roar', 'Seongnam FC', 'SV Ried', 'CD Huachipato',
       'WSG Tirol', 'Podbeskidzie Bielsko-Biała', 'Peterborough United',
       'Club Blooming', 'Wisła Płock', 'Busan IPark', 'FSV Zwickau',
       'Mjøndalen IF', 'Vejle Boldklub', 'Pau FC', 'FC Lausanne-Sport',
       'Estudiantes de Mérida', 'Sagan Tosu', 'SV Waldhof Mannheim',
       'Sport Huancayo', 'Hallescher FC', 'Kalmar FF', 'St. Mirren',
       'SKN St. Pölten', 'Sarpsborg 08 FF', 'Shrewsbury',
       'TSV 1860 München', 'SV Meppen', 'Ipswich Town', 'IK Start',
       'Adelaide United', 'Stal Mielec', 'Centro Atlético Fénix',
       'Newcastle Jets', 'Livingston FC', 'AC Mineros de Guayana',
       'AFC Wimbledon', 'Burton Albion', 'Al Adalah', 'Warta Poznań',
       'USL Dunkerque', 'Bristol Rovers', 'UTA Arad', 'Östersunds FK',
       'Sportivo Luqueño', 'Politehnica Iaşi', 'Salford City',
       'Central Coast Mariners', 'Caracas FC', 'AC Horsens',
       'Plymouth Argyle', 'Aalesunds FK', 'Crewe Alexandra',
       'Chindia Târgovişte', 'Oldham Athletic', 'Yokohama FC',
       'Blackpool', 'Northampton Town', 'Bayern München II',
       'FK Haugesund', 'KFC Uerdingen 05', 'Forest Green Rovers',
       'Cheltenham Town', 'Strømsgodset IF', 'Mjällby AIF', 'Exeter City',
       'Cambridge United', 'Grimsby Town', 'FC Vaduz', 'Türkgücü München',
       'VfB Lübeck', 'Bolton Wanderers', 'Bradford City',
       '1. FC Magdeburg', 'FC Admira Wacker Mödling',
       'Hamilton Academical FC', 'Aragua FC', 'Accrington Stanley',
       'Swindon Town', 'Carlisle United', 'FC Argeș', 'Port Vale',
       'Academica Clinceni', 'Rochdale', 'Gillingham', 'Tranmere Rovers',
       'Southend United', '1. FC Saarbrücken', 'Colchester United',
       'Mansfield Town', 'Falkenbergs FF', 'SC Verl', 'Varbergs BoIS',
       'Crawley Town', 'Sandefjord Fotball', 'Newport County',
       'Bohemian FC', 'Ross County FC', 'Scunthorpe United', 'Morecambe',
       'Walsall', 'Leyton Orient', 'Stevenage', 'Barrow', 'Derry City',
       'Llaneros de Guanare', 'Sligo Rovers', 'Zamora FC',
       "St. Patrick's Athletic", 'Cork City', 'Shelbourne FC',
       'Harrogate Town', 'Waterford FC', 'Finn Harps'], dtype=object)

In [ ]:
#checking for names that start with numbers
fifa_df["Club"][fifa_df["Club"].str.contains(r"^\d+")].value_counts()

1. FSV Mainz 05          32
1. FC Köln               31
1. FC Nürnberg           30
1. FC Heidenheim 1846    30
1. FC Union Berlin       28
1. FC Kaiserslautern     28
1. FC Magdeburg          28
1. FC Saarbrücken        27
Name: Club, dtype: int64

In [ ]:
import re

In [ ]:
# Remove "1. "
fifa_df["Club"] = fifa_df["Club"].apply(lambda x: pd.Series(re.sub(pattern = r"^\d+\. ", string=x, repl="")))

#### 4.4 Can you clean and transform the value, wage, and release clause columns into columns of integers?

In [ ]:
fifa_df.loc[:, ['Value', 'Wage', 'Release Clause']]

         Value   Wage Release Clause
0      €103.5M  €560K        €138.4M
1         €63M  €220K         €75.9M
2        €120M  €125K        €159.4M
3        €129M  €370K          €161M
4        €132M  €270K        €166.5M
...        ...    ...            ...
18974    €100K    €1K           €70K
18975    €130K   €500          €165K
18976    €120K   €500          €131K
18977    €100K    €2K           €88K
18978    €100K    €1K           €79K

[18979 rows x 3 columns]

In [ ]:
fifa_df['Wage'].unique()

array(['€560K', '€220K', '€125K', '€370K', '€270K', '€240K', '€250K',
       '€160K', '€260K', '€210K', '€310K', '€130K', '€350K', '€300K',
       '€190K', '€145K', '€195K', '€100K', '€140K', '€290K', '€82K',
       '€110K', '€230K', '€155K', '€200K', '€165K', '€95K', '€170K',
       '€105K', '€115K', '€150K', '€135K', '€55K', '€58K', '€81K', '€34K',
       '€120K', '€59K', '€90K', '€65K', '€56K', '€71K', '€18K', '€75K',
       '€47K', '€20K', '€84K', '€86K', '€74K', '€78K', '€27K', '€68K',
       '€85K', '€25K', '€46K', '€83K', '€54K', '€79K', '€175K', '€43K',
       '€49K', '€45K', '€38K', '€41K', '€39K', '€23K', '€51K', '€50K',
       '€87K', '€30K', '€14K', '€69K', '€31K', '€64K', '€53K', '€35K',
       '€21K', '€28K', '€17K', '€33K', '€70K', '€32K', '€89K', '€26K',
       '€40K', '€76K', '€72K', '€48K', '€36K', '€29K', '€60K', '€16K',
       '€37K', '€24K', '€52K', '€0', '€62K', '€73K', '€63K', '€19K',
       '€1K', '€66K', '€80K', '€12K', '€2K', '€42K', '€13K', '€900',
       '€57K', '€77K', '€61K', '€22K', '€67K', '€44K', '€15K', '€11K',
       '€8K', '€850', '€10K', '€88K', '€500', '€7K', '€6K', '€9K', '€5K',
       '€700', '€950', '€750', '€3K', '€650', '€600', '€4K', '€800',
       '€550'], dtype=object)

In [ ]:
fifa_df['Value'].unique()

array(['€103.5M', '€63M', '€120M', '€129M', '€132M', '€111M', '€120.5M',
       '€102M', '€185.5M', '€110M', '€113M', '€90.5M', '€82M', '€17.5M',
       '€83.5M', '€33.5M', '€114.5M', '€78M', '€103M', '€109M', '€92M',
       '€10M', '€76.5M', '€89.5M', '€87.5M', '€79.5M', '€124M', '€114M',
       '€95M', '€92.5M', '€105.5M', '€88.5M', '€85M', '€81.5M', '€26M',
       '€21M', '€56M', '€67.5M', '€53M', '€36.5M', '€51M', '€65.5M',
       '€46.5M', '€61.5M', '€72.5M', '€77.5M', '€43.5M', '€32.5M', '€36M',
       '€32M', '€54M', '€49.5M', '€57M', '€66.5M', '€74.5M', '€71.5M',
       '€121M', '€99M', '€67M', '€86.5M', '€93.5M', '€70M', '€62M',
       '€66M', '€58M', '€44M', '€81M', '€37M', '€14.5M', '€46M', '€47.5M',
       '€52.5M', '€54.5M', '€34.5M', '€57.5M', '€51.5M', '€44.5M', '€55M',
       '€48M', '€60.5M', '€63.5M', '€61M', '€29M', '€58.5M', '€55.5M',
       '€42M', '€40.5M', '€43M', '€45.5M', '€34M', '€26.5M', '€42.5M',
       '€35.5M', '€45M', '€41.5M', '€40M', '€11M', '€13.5M', '€29.5M',
       '€27M', '€15.5M', '€38.5M', '€52M', '€33M', '€19M', '€73.5M',
       '€38M', '€35M', '€47M', '€24M', '€30.5M', '€18M', '€28M', '€25.5M',
       '€25M', '€31M', '€23.5M', '€30M', '€31.5M', '€22.5M', '€28.5M',
       '€4M', '€12.5M', '€37.5M', '€27.5M', '€16M', '€15M', '€20.5M',
       '€22M', '€3.4M', '€5M', '€56.5M', '€62.5M', '€0', '€39M', '€24.5M',
       '€21.5M', '€13M', '€8M', '€20M', '€8.5M', '€2.9M', '€9M', '€4.6M',
       '€50M', '€23M', '€18.5M', '€7M', '€19.5M', '€5.5M', '€7.5M',
       '€3.8M', '€14M', '€10.5M', '€16.5M', '€3.6M', '€9.5M', '€39.5M',
       '€17M', '€12M', '€11.5M', '€4.9M', '€3M', '€1.9M', '€6.5M',
       '€1.7M', '€2.4M', '€3.1M', '€6M', '€3.7M', '€4.7M', '€4.3M',
       '€2.1M', '€1.2M', '€1.8M', '€4.8M', '€3.2M', '€1.3M', '€825K',
       '€2.3M', '€1.5M', '€3.9M', '€2.6M', '€3.5M', '€2.8M', '€2.7M',
       '€4.4M', '€4.1M', '€950K', '€1.6M', '€625K', '€1.1M', '€4.5M',
       '€4.2M', '€2.2M', '€3.3M', '€1.4M', '€2M', '€475K', '€925K',
       '€750K', '€725K', '€2.5M', '€1M', '€350K', '€525K', '€600K',
       '€850K', '€800K', '€550K', '€250K', '€400K', '€425K', '€575K',
       '€210K', '€325K', '€900K', '€875K', '€650K', '€700K', '€500K',
       '€975K', '€375K', '€775K', '€275K', '€180K', '€450K', '€675K',
       '€150K', '€240K', '€300K', '€130K', '€220K', '€200K', '€110K',
       '€170K', '€230K', '€90K', '€120K', '€80K', '€190K', '€140K',
       '€160K', '€100K', '€60K', '€50K', '€70K', '€45K', '€35K', '€40K',
       '€25K', '€20K', '€15K', '€30K', '€9K'], dtype=object)

In [ ]:
fifa_df['Release Clause'].unique()

array(['€138.4M', '€75.9M', '€159.4M', ..., '€59K', '€35K', '€64K'],
      dtype=object)

As seen above,columns have the some values in thousands (K) and millions (M) Which have to converted and the currency symbols removed.

In [ ]:
def object_to_float(x):
  if isinstance(x, str):
    #If K is present at the last index
    if x.find('K') != -1:
      #replace K and € with empty string
      x = x.replace('K', '').replace('€','')
      #multiply with 1000 to ensure it's in thousands
      return float(x)*1000
     #If M is present
    elif x.find('M') != -1:
      x= x.replace('M','').replace('€','')
       #multiply with 10e6 to ensure it's in millions
      return float(x)*10e6
    elif x.find('€') != -1:
      x = x.replace('€','')
      return float(x)
    else:
      return x
  else:
    return x

In [ ]:
fifa_df['Value(€)'] = fifa_df['Value'].apply(object_to_float)
fifa_df['Value(€)'].unique

<bound method Series.unique of 0        1.035000e+09
1        6.300000e+08
2        1.200000e+09
3        1.290000e+09
4        1.320000e+09
             ...
18974    1.000000e+05
18975    1.300000e+05
18976    1.200000e+05
18977    1.000000e+05
18978    1.000000e+05
Name: Value(€), Length: 18979, dtype: float64>

In [ ]:
fifa_df['Wage(€)'] = fifa_df['Wage'].apply(object_to_float)
fifa_df['Wage(€)'].unique

<bound method Series.unique of 0        560000.0
1        220000.0
2        125000.0
3        370000.0
4        270000.0
           ...
18974      1000.0
18975       500.0
18976       500.0
18977      2000.0
18978      1000.0
Name: Wage(€), Length: 18979, dtype: float64>

In [ ]:
fifa_df['Release Clause(€)'] = fifa_df['Release Clause'].apply(object_to_float)
fifa_df['Release Clause(€)'].unique

<bound method Series.unique of 0        1.384000e+09
1        7.590000e+08
2        1.594000e+09
3        1.610000e+09
4        1.665000e+09
             ...
18974    7.000000e+04
18975    1.650000e+05
18976    1.310000e+05
18977    8.800000e+04
18978    7.900000e+04
Name: Release Clause(€), Length: 18979, dtype: float64>

In [ ]:
# converting from float to int
fifa_df = fifa_df.astype({"Wage(€)":"int","Value(€)":"int","Release Clause(€)":"int"})
print(fifa_df.dtypes)

ID                    int64
Name                 object
Age                   int64
↓OVA                  int64
POT                   int64
                      ...
Month                 int64
Year                  int64
Value(€)              int64
Wage(€)               int64
Release Clause(€)     int64
Length: 78, dtype: object

In [ ]:
fifa_df.columns

Index(['ID', 'Name', 'Age', '↓OVA', 'POT', 'Club', 'Contract', 'Positions',
       'Height', 'Weight', 'Preferred Foot', 'BOV', 'Best Position',
       'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Attacking',
       'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility',
       'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina',
       'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions',
       'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W',
       'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits', 'Day', 'Month',
       'Year', 'Value(€)', 'Wage(€)', 'Release Clause(€)'],
      dtype='object')

In [ ]:
#dropping the replaced columns
fifa_df.drop(columns=['Value','Wage','Release Clause'], inplace=True)
fifa_df.columns

Index(['ID', 'Name', 'Age', '↓OVA', 'POT', 'Club', 'Contract', 'Positions',
       'Height', 'Weight', 'Preferred Foot', 'BOV', 'Best Position',
       'Loan Date End', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits', 'Day', 'Month', 'Year', 'Value(€)',
       'Wage(€)', 'Release Clause(€)'],
      dtype='object')

In [ ]:
fifa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 75 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 18979 non-null  int64
 1   Name               18979 non-null  object
 2   Age                18979 non-null  int64
 3   ↓OVA               18979 non-null  int64
 4   POT                18979 non-null  int64
 5   Club               18979 non-null  object
 6   Contract           18979 non-null  object
 7   Positions          18979 non-null  object
 8   Height             18979 non-null  object
 9   Weight             18979 non-null  object
 10  Preferred Foot     18979 non-null  object
 11  BOV                18979 non-null  int64
 12  Best Position      18979 non-null  object
 13  Loan Date End      1013 non-null   object
 14  Attacking          18979 non-null  int64
 15  Crossing           18979 non-null  int64
 16  Finishing          18979 non-null  int64
 17  Heading Accuracy   18979 non-null  int64
 18  Short Passing      18979 non-null  int64
 19  Volleys            18979 non-null  int64
 20  Skill              18979 non-null  int64
 21  Dribbling          18979 non-null  int64
 22  Curve              18979 non-null  int64
 23  FK Accuracy        18979 non-null  int64
 24  Long Passing       18979 non-null  int64
 25  Ball Control       18979 non-null  int64
 26  Movement           18979 non-null  int64
 27  Acceleration       18979 non-null  int64
 28  Sprint Speed       18979 non-null  int64
 29  Agility            18979 non-null  int64
 30  Reactions          18979 non-null  int64
 31  Balance            18979 non-null  int64
 32  Power              18979 non-null  int64
 33  Shot Power         18979 non-null  int64
 34  Jumping            18979 non-null  int64
 35  Stamina            18979 non-null  int64
 36  Strength           18979 non-null  int64
 37  Long Shots         18979 non-null  int64
 38  Mentality          18979 non-null  int64
 39  Aggression         18979 non-null  int64
 40  Interceptions      18979 non-null  int64
 41  Positioning        18979 non-null  int64
 42  Vision             18979 non-null  int64
 43  Penalties          18979 non-null  int64
 44  Composure          18979 non-null  int64
 45  Defending          18979 non-null  int64
 46  Marking            18979 non-null  int64
 47  Standing Tackle    18979 non-null  int64
 48  Sliding Tackle     18979 non-null  int64
 49  Goalkeeping        18979 non-null  int64
 50  GK Diving          18979 non-null  int64
 51  GK Handling        18979 non-null  int64
 52  GK Kicking         18979 non-null  int64
 53  GK Positioning     18979 non-null  int64
 54  GK Reflexes        18979 non-null  int64
 55  Total Stats        18979 non-null  int64
 56  Base Stats         18979 non-null  int64
 57  W/F                18979 non-null  object
 58  SM                 18979 non-null  object
 59  A/W                18979 non-null  object
 60  D/W                18979 non-null  object
 61  IR                 18979 non-null  object
 62  PAC                18979 non-null  int64
 63  SHO                18979 non-null  int64
 64  PAS                18979 non-null  int64
 65  DRI                18979 non-null  int64
 66  DEF                18979 non-null  int64
 67  PHY                18979 non-null  int64
 68  Hits               16384 non-null  object
 69  Day                18979 non-null  int64
 70  Month              18979 non-null  int64
 71  Year               18979 non-null  int64
 72  Value(€)           18979 non-null  int64
 73  Wage(€)            18979 non-null  int64
 74  Release Clause(€)  18979 non-null  int64
dtypes: int64(60), object(15)
memory usage: 10.9+ MB

#### 4.5 Does the `hits` column have the correct datatype?

In [ ]:
#checking for number  null values
fifa_df["Hits"].isna().sum()

2595

In [ ]:
fifa_df["Hits"].unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', '1.6K',
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', '1.1K', '433', '242', '206', '177', '1.5K', '198', '459',
       '117', '119', '209', '84', '187', '165', '203', '65', '336', '126',
       '313', '124', '145', '538', '182', '101', '45', '377', '99', '194',
       '403', '414', '593', '374', '245', '3.2K', '266', '299', '309',
       '215', '265', '211', '112', '337', '70', '159', '688', '116', '63',
       '144', '123', '71', '224', '113', '168', '61', '89', '137', '278',
       '75', '148', '176', '197', '264', '214', '247', '402', '440',
       '1.7K', '2.3K', '171', '320', '657', '87', '259', '200', '255',
       '253', '196', '60', '97', '85', '169', '256', '132', '239', '166',
       '121', '109', '32', '46', '122', '48', '527', '199', '282', '51',
       '1.9K', '642', '155', '323', '288', '497', '509', '79', '49',
       '270', '511', '80', '128', '115', '156', '204', '143', '140',
       '152', '220', '134', '225', '94', '74', '135', '142', '50', '77',
       '40', '107', '193', '179', '34', '64', '453', '57', '81', '28',
       '78', '133', '43', '425', '88', '42', '36', '233', '376', '210',
       '444', '100', '263', '98', '29', '160', '39', '257', '6', '310',
       '138', '62', '293', '285', '362', '66', '69', '58', '21', '20',
       '131', '38', '406', '68', '108', '110', '93', '512', '443', '306',
       '352', '422', '585', '346', '178', '841', '76', '394', '72', '172',
       '44', '407', '230', '367', '295', '157', '243', '56', '111', '326',
       '679', '18', '92', '59', '25', '184', '53', '12', '90', '55', '73',
       '11', '566', '180', '83', '262', '17', '26', '31', '280', '359',
       '213', '297', '387', '480', '381', '677', '486', '8', '244', '129',
       '388', '275', '319', '2K', '52', '91', '421', '153', '27', '41',
       '222', '35', '102', '23', '30', '33', '146', '13', '19', '14',
       '106', '276', '568', '353', '47', '478', '249', '254', '369',
       '219', '565', '237', '227', '434', '375', '162', '605', '654', '3',
       '7', '9', '104', '114', '186', '446', '756', '22', '139', '500',
       '67', '147', '149', '16', '82', '54', '37', '15', '1.3K', '3K',
       '952', '5', '749', '541', '330', '393', '517', '770', '409', '170',
       '125', '283', '342', '363', '580', '105', '217', '24', '141', '10',
       '427', '158', '426', '4', '666', '181', '324', '979', '1.4K',
       '302', '751', '298', '411', '944', '2', '947', '292', '349', '621',
       '1', '2.8K', '338', '287', '261', '218', '1.8K', '240', '279',
       '229', '188', '315', '664', '613', '190', '706', '127', '462',
       '386', '695', '491', '167', '281', '250', '307', '95', '231',
       '174', '680', '633', '221', '348', '602', '183', '653', '195',
       '164', '151', '258', '8.4K', '343', '419', '655', '136', '399',
       '531', '357', '228', '385', '312', '340', '238', '487', '355',
       '499', '4.3K', '296', '515', '943', '1.2K', '903', '335', '191',
       '594', '267', '617', '516', '504', '331', '652', '410', '550',
       '473', '442', '344', '208', '1K', '2.5K', '273', '485', '826',
       '192', '405', '941', '477', '644', '303', '417', '6K', nan, 11.0,
       2.0, 1.0, 31.0, 3.0, 10.0, 9.0, 17.0, 7.0, 4.0, 6.0], dtype=object)

In [ ]:
# putting the values in correct format by replacing the strings with K in correct numerical format
def cleanHit(x):
    if isinstance(x, str) and "K" in x:
        x = x.replace('K', "")
        x = float(x) * 1000
        return round(x)
    else:
        return x

In [ ]:
fifa_df["Hits"] = fifa_df["Hits"].apply(cleanHit)
fifa_df["Hits"].unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', 1600,
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', 1100, '433', '242', '206', '177', 1500, '198', '459', '117',
       '119', '209', '84', '187', '165', '203', '65', '336', '126', '313',
       '124', '145', '538', '182', '101', '45', '377', '99', '194', '403',
       '414', '593', '374', '245', 3200, '266', '299', '309', '215',
       '265', '211', '112', '337', '70', '159', '688', '116', '63', '144',
       '123', '71', '224', '113', '168', '61', '89', '137', '278', '75',
       '148', '176', '197', '264', '214', '247', '402', '440', 1700, 2300,
       '171', '320', '657', '87', '259', '200', '255', '253', '196', '60',
       '97', '85', '169', '256', '132', '239', '166', '121', '109', '32',
       '46', '122', '48', '527', '199', '282', '51', 1900, '642', '155',
       '323', '288', '497', '509', '79', '49', '270', '511', '80', '128',
       '115', '156', '204', '143', '140', '152', '220', '134', '225',
       '94', '74', '135', '142', '50', '77', '40', '107', '193', '179',
       '34', '64', '453', '57', '81', '28', '78', '133', '43', '425',
       '88', '42', '36', '233', '376', '210', '444', '100', '263', '98',
       '29', '160', '39', '257', '6', '310', '138', '62', '293', '285',
       '362', '66', '69', '58', '21', '20', '131', '38', '406', '68',
       '108', '110', '93', '512', '443', '306', '352', '422', '585',
       '346', '178', '841', '76', '394', '72', '172', '44', '407', '230',
       '367', '295', '157', '243', '56', '111', '326', '679', '18', '92',
       '59', '25', '184', '53', '12', '90', '55', '73', '11', '566',
       '180', '83', '262', '17', '26', '31', '280', '359', '213', '297',
       '387', '480', '381', '677', '486', '8', '244', '129', '388', '275',
       '319', 2000, '52', '91', '421', '153', '27', '41', '222', '35',
       '102', '23', '30', '33', '146', '13', '19', '14', '106', '276',
       '568', '353', '47', '478', '249', '254', '369', '219', '565',
       '237', '227', '434', '375', '162', '605', '654', '3', '7', '9',
       '104', '114', '186', '446', '756', '22', '139', '500', '67', '147',
       '149', '16', '82', '54', '37', '15', 1300, 3000, '952', '5', '749',
       '541', '330', '393', '517', '770', '409', '170', '125', '283',
       '342', '363', '580', '105', '217', '24', '141', '10', '427', '158',
       '426', '4', '666', '181', '324', '979', 1400, '302', '751', '298',
       '411', '944', '2', '947', '292', '349', '621', '1', 2800, '338',
       '287', '261', '218', 1800, '240', '279', '229', '188', '315',
       '664', '613', '190', '706', '127', '462', '386', '695', '491',
       '167', '281', '250', '307', '95', '231', '174', '680', '633',
       '221', '348', '602', '183', '653', '195', '164', '151', '258',
       8400, '343', '419', '655', '136', '399', '531', '357', '228',
       '385', '312', '340', '238', '487', '355', '499', 4300, '296',
       '515', '943', 1200, '903', '335', '191', '594', '267', '617',
       '516', '504', '331', '652', '410', '550', '473', '442', '344',
       '208', 1000, 2500, '273', '485', '826', '192', '405', '941', '477',
       '644', '303', '417', 6000, nan, 11.0, 2.0, 1.0, 31.0, 3.0, 10.0,
       9.0, 17.0, 7.0, 4.0, 6.0], dtype=object)

In [ ]:
#filling null values with 0
fifa_df['Hits'] = fifa_df['Hits'].fillna(0)

In [ ]:
#converting hits from object to int
fifa_df['Hits'] = fifa_df['Hits'].astype('int64')
type(fifa_df['Hits'][0])

numpy.int64

In [ ]:
fifa_df["Hits"].unique()

array([ 771,  562,  150,  207,  595,  248,  246,  120, 1600,  130,  321,
        189,  175,   96,  118,  216,  212,  154,  205,  202,  339,  408,
        103,  332,   86,  173,  161,  396, 1100,  433,  242,  206,  177,
       1500,  198,  459,  117,  119,  209,   84,  187,  165,  203,   65,
        336,  126,  313,  124,  145,  538,  182,  101,   45,  377,   99,
        194,  403,  414,  593,  374,  245, 3200,  266,  299,  309,  215,
        265,  211,  112,  337,   70,  159,  688,  116,   63,  144,  123,
         71,  224,  113,  168,   61,   89,  137,  278,   75,  148,  176,
        197,  264,  214,  247,  402,  440, 1700, 2300,  171,  320,  657,
         87,  259,  200,  255,  253,  196,   60,   97,   85,  169,  256,
        132,  239,  166,  121,  109,   32,   46,  122,   48,  527,  199,
        282,   51, 1900,  642,  155,  323,  288,  497,  509,   79,   49,
        270,  511,   80,  128,  115,  156,  204,  143,  140,  152,  220,
        134,  225,   94,   74,  135,  142,   50,   77,   40,  107,  193,
        179,   34,   64,  453,   57,   81,   28,   78,  133,   43,  425,
         88,   42,   36,  233,  376,  210,  444,  100,  263,   98,   29,
        160,   39,  257,    6,  310,  138,   62,  293,  285,  362,   66,
         69,   58,   21,   20,  131,   38,  406,   68,  108,  110,   93,
        512,  443,  306,  352,  422,  585,  346,  178,  841,   76,  394,
         72,  172,   44,  407,  230,  367,  295,  157,  243,   56,  111,
        326,  679,   18,   92,   59,   25,  184,   53,   12,   90,   55,
         73,   11,  566,  180,   83,  262,   17,   26,   31,  280,  359,
        213,  297,  387,  480,  381,  677,  486,    8,  244,  129,  388,
        275,  319, 2000,   52,   91,  421,  153,   27,   41,  222,   35,
        102,   23,   30,   33,  146,   13,   19,   14,  106,  276,  568,
        353,   47,  478,  249,  254,  369,  219,  565,  237,  227,  434,
        375,  162,  605,  654,    3,    7,    9,  104,  114,  186,  446,
        756,   22,  139,  500,   67,  147,  149,   16,   82,   54,   37,
         15, 1300, 3000,  952,    5,  749,  541,  330,  393,  517,  770,
        409,  170,  125,  283,  342,  363,  580,  105,  217,   24,  141,
         10,  427,  158,  426,    4,  666,  181,  324,  979, 1400,  302,
        751,  298,  411,  944,    2,  947,  292,  349,  621,    1, 2800,
        338,  287,  261,  218, 1800,  240,  279,  229,  188,  315,  664,
        613,  190,  706,  127,  462,  386,  695,  491,  167,  281,  250,
        307,   95,  231,  174,  680,  633,  221,  348,  602,  183,  653,
        195,  164,  151,  258, 8400,  343,  419,  655,  136,  399,  531,
        357,  228,  385,  312,  340,  238,  487,  355,  499, 4300,  296,
        515,  943, 1200,  903,  335,  191,  594,  267,  617,  516,  504,
        331,  652,  410,  550,  473,  442,  344,  208, 1000, 2500,  273,
        485,  826,  192,  405,  941,  477,  644,  303,  417, 6000,    0])

#### 4.6 How can you make the contract column better?

In [ ]:
fifa_df["Contract"].unique()

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2017 ~ 2023', '2018 ~ 2024', '2014 ~ 2022',
       '2018 ~ 2023', '2016 ~ 2023', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2012 ~ 2021', '2019 ~ 2024',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022', '2012 ~ 2022',
       '2016 ~ 2025', '2013 ~ 2022', '2011 ~ 2022', '2012 ~ 2024',
       '2016 ~ 2021', '2012 ~ 2023', '2008 ~ 2022', '2019 ~ 2022',
       '2017 ~ 2021', '2013 ~ 2024', '2020 ~ 2024', '2010 ~ 2022',
       '2020 ~ 2021', '2011 ~ 2024', '2020 ~ 2023', '2014 ~ 2024',
       '2013 ~ 2026', '2016 ~ 2022', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 On Loan',
       '2009 ~ 2021', '2019 ~ 2021', '2019 ~ 2026', 'Free', '2012 ~ 2028',
       '2010 ~ 2023', '2014 ~ 2021', '2015 ~ 2025', '2014 ~ 2026',
       '2012 ~ 2025', '2017 ~ 2020', '2002 ~ 2022', '2020 ~ 2027',
       '2013 ~ 2025', 'Dec 31, 2020 On Loan', '2019 ~ 2020',
       '2011 ~ 2025', '2016 ~ 2020', '2007 ~ 2021', '2020 ~ 2026',
       '2010 ~ 2025', '2009 ~ 2023', '2008 ~ 2021', '2020 ~ 2020',
       '2016 ~ 2026', 'Jan 30, 2021 On Loan', '2012 ~ 2020',
       '2014 ~ 2025', 'Jun 30, 2022 On Loan', '2015 ~ 2020',
       'May 31, 2021 On Loan', '2018 ~ 2020', '2014 ~ 2020',
       '2013 ~ 2020', '2006 ~ 2024', 'Jul 5, 2021 On Loan',
       'Dec 31, 2021 On Loan', '2004 ~ 2025', '2011 ~ 2020',
       'Jul 1, 2021 On Loan', 'Jan 1, 2021 On Loan', '2006 ~ 2023',
       'Aug 31, 2021 On Loan', '2006 ~ 2021', '2005 ~ 2023',
       '2003 ~ 2020', '2009 ~ 2020', '2002 ~ 2020', '2005 ~ 2020',
       '2005 ~ 2022', 'Jan 31, 2021 On Loan', '2010 ~ 2020',
       'Dec 30, 2021 On Loan', '2008 ~ 2020', '2007 ~ 2020',
       '2003 ~ 2021', 'Jun 23, 2021 On Loan', 'Jan 3, 2021 On Loan',
       'Nov 27, 2021 On Loan', '2002 ~ 2021', 'Jan 17, 2021 On Loan',
       'Jun 30, 2023 On Loan', '1998 ~ 2021', '2003 ~ 2022',
       '2007 ~ 2023', 'Jul 31, 2021 On Loan', 'Nov 22, 2020 On Loan',
       'May 31, 2022 On Loan', '2006 ~ 2020', 'Dec 30, 2020 On Loan',
       '2007 ~ 2025', 'Jan 4, 2021 On Loan', 'Nov 30, 2020 On Loan',
       '2004 ~ 2020', '2009 ~ 2025', 'Aug 1, 2021 On Loan'], dtype=object)

It can be observed that some players have an active contract with their clubs while others are either on loan or are free. These players' contracts can be categorized into active, on_loan and free respectively.

In [ ]:
# function to categorise contracts
def categoriseContracts(x):
  #active contracts
  if "~" in x:
    x = "active"
    return x
  #on loan
  elif "On Loan" in x:
    x = "on_loan"
    return x
  #free
  elif "Free" in x:
    x = "free"
    return x

In [ ]:
fifa_df['Contract'] = fifa_df['Contract'].apply(categoriseContracts)
#rename contract to contract status
fifa_df = fifa_df.rename(columns={"Contract": "Contract_Status"})
#converting to category type
fifa_df["Contract_Status"] =  fifa_df["Contract_Status"].astype("category")
fifa_df.head()

,ID,Name,Age,↓OVA,POT,Club,Contract_Status,Positions,Height,Weight,...,DRI,DEF,PHY,Hits,Day,Month,Year,Value(€),Wage(€),Release Clause(€)
0,158023,L. Messi,33,93,93,FC Barcelona,active,"RW, ST, CF",170cm,72kg,...,95,38,65,771,1,7,2004,1035000000,560000,1384000000
1,20801,Cristiano Ronaldo,35,92,92,Juventus,active,"ST, LW",187cm,83kg,...,89,35,77,562,10,7,2018,630000000,220000,759000000
2,200389,J. Oblak,27,91,93,Atlético Madrid,active,GK,188cm,87kg,...,90,52,90,150,16,7,2014,1200000000,125000,1594000000
3,192985,K. De Bruyne,29,91,91,Manchester City,active,"CAM, CM",181cm,70kg,...,88,64,78,207,30,8,2015,1290000000,370000,1610000000
4,190871,Neymar Jr,28,91,91,Paris Saint-Germain,active,"LW, CAM",175cm,68kg,...,94,36,59,595,3,8,2017,1320000000,270000,1665000000

#### 4.7 Do the height and weight columns have the appropriate data types?

In [ ]:
fifa_df['Height'].dtypes

dtype('O')

In [ ]:
fifa_df['Weight'].dtypes

dtype('O')

The height and weight columns both have object data types. The Object data type is usually used to store strings and mixed values. This is beacuse the values are save using their units i.e height is saved in cm while weight in kg. These columns don't have the appropriate data types as height and weight are numerical parameters usually represented using float64 or int64 data types.
The columns need to be cleaned.

In [ ]:
fifa_df[['Height','Weight']]

      Height Weight
0      170cm   72kg
1      187cm   83kg
2      188cm   87kg
3      181cm   70kg
4      175cm   68kg
...      ...    ...
18974  178cm   66kg
18975  175cm   65kg
18976  179cm   74kg
18977  175cm   69kg
18978  188cm   75kg

[18979 rows x 2 columns]

In [ ]:
fifa_df['Height'].unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

In [ ]:
fifa_df['Weight'].unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [ ]:
# Function to convert height to cm
def heightConversion(x):
  if x[-1] == "m":
    return int(x[:-2])
  elif x[-1] == '"':
    #replacing " with empty space
    x = x.replace("\"","")
    #converting the inches part of height to cm (1 inch= 2.54cm)
    height_inches = int(x[2:])* 2.54
    #converting foot part of height to cm (1 foot= 30.48cm)
    height_foot = int(x[0])*30.48
    return round(height_foot+height_inches)

In [ ]:
fifa_df["Height(cm)"] = fifa_df["Height"].apply(heightConversion)
fifa_df["Height(cm)"].unique()

array([170, 187, 188, 181, 175, 184, 191, 178, 193, 185, 199, 173, 168,
       176, 177, 183, 180, 189, 179, 195, 172, 182, 186, 192, 165, 194,
       167, 196, 163, 190, 174, 169, 171, 197, 200, 166, 164, 198, 201,
       158, 162, 161, 160, 203, 157, 156, 202, 159, 206, 155])

In [ ]:
fifa_df.drop("Height",axis=1, inplace=True)

In [ ]:

#Function to convert the weight to kg
def weightConversion(x):
  if "lbs" in x:
    x = x.replace('lbs','')
    x = float(x)*0.453592
    x = int(x)
    return x
  else:
    return int(x[:-2])

In [ ]:
fifa_df["Weight(kg)"] = fifa_df["Weight"].apply(weightConversion)
fifa_df["Weight(kg)"].unique()

array([ 72,  83,  87,  70,  68,  80,  71,  91,  73,  85,  92,  69,  84,
        96,  81,  82,  75,  86,  89,  74,  76,  64,  78,  90,  66,  60,
        94,  79,  67,  65,  59,  61,  93,  88,  97,  77,  62,  63,  95,
       100,  58,  98, 103,  99, 102,  56, 101,  57,  55, 104, 107, 110,
        53,  50,  54,  52])

In [ ]:
fifa_df.drop("Weight",axis=1, inplace=True)

#### 4.7 Cleaning the `Positions` column

In [ ]:
fifa_df.columns

Index(['ID', 'Name', 'Age', '↓OVA', 'POT', 'Club', 'Contract_Status',
       'Positions', 'Preferred Foot', 'BOV', 'Best Position', 'Loan Date End',
       'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy',
       'Short Passing', 'Volleys', 'Skill', 'Dribbling', 'Curve',
       'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits', 'Day', 'Month', 'Year', 'Value(€)',
       'Wage(€)', 'Release Clause(€)', 'Height(cm)', 'Weight(kg)'],
      dtype='object')

In [ ]:
fifa_df["Positions"].unique()

array(['RW, ST, CF', 'ST, LW', 'GK', 'CAM, CM', 'LW, CAM', 'ST', 'RW',
       'ST, LW, RW', 'CB', 'LW', 'CDM', 'CF, ST', 'LW, RW', 'CDM, CM',
       'CDM, RB', 'CF, CAM', 'LW, ST', 'CM', 'ST, CF, LW', 'RM, LM, CAM',
       'RB', 'RW, CAM, CM', 'LB', 'LM, CF', 'CF', 'RW, LW', 'CAM, RM, RW',
       'CM, CDM', 'CAM, CF, ST', 'CM, CDM, CAM', 'CF, LW, CAM',
       'CAM, RM, CF', 'LM, ST', 'RM, LM, RW', 'LM', 'CAM, RW', 'CB, CDM',
       'RW, RM', 'LW, CF', 'CM, RM, LM', 'LB, LM', 'CAM, CM, RM',
       'CAM, CM, CF', 'CAM, CF', 'LM, RM, LW', 'LM, LB, CM', 'CM, LM, LB',
       'RM, RW', 'RM, CM', 'CAM, CM, LW', 'CB, LB', 'RM, RB', 'ST, RW',
       'LM, RW, LW', 'RB, LB', 'RB, RM', 'RM', 'LM, RM, CF', 'CAM, RM',
       'RB, RWB', 'CDM, CB, CM', 'CAM, RM, ST', 'LM, LW, RM', 'CM, CAM',
       'ST, RM, CF', 'LM, RM', 'RM, CF', 'LM, LWB', 'RW, RM, CF',
       'RB, CM', 'LW, CAM, RW', 'CAM, LW, CM', 'CM, CAM, CDM',
       'RW, LW, CAM', 'CM, CAM, LM', 'CM, RM, ST', 'CDM, CM, RB',
       'ST, CAM', 'CAM, LW, ST', 'LB, CB, LWB', 'RM, ST', 'CB, CDM, LB',
       'RWB, RM', 'CM, LM, RM', 'RB, CDM, CM', 'RW, LW, RM', 'LM, LW',
       'CM, LM', 'LM, LB', 'RM, LM, CF', 'LB, LM, RM', 'CDM, CM, CAM',
       'ST, LW, RM', 'CAM, CM, ST', 'ST, CF', 'LWB, LB', 'LW, RW, LM',
       'RM, RW, ST', 'LWB', 'CF, ST, CAM', 'LM, CAM, RM', 'RB, CB',
       'ST, LM', 'RW, CAM', 'LM, CAM', 'RWB, RB', 'ST, RW, LW', 'CAM',
       'RB, RM, RW', 'LB, LWB', 'RM, CAM', 'CAM, ST', 'CDM, CB',
       'CF, LM, LW', 'CAM, LM, LW', 'LW, RW, CAM', 'CB, RB',
       'RB, CB, RWB', 'LM, LW, ST', 'LW, ST, CM', 'RM, CAM, CM',
       'CB, RB, RWB', 'RW, ST, LW', 'LW, CAM, CM', 'CM, LM, CDM',
       'LB, LM, LWB', 'CB, LB, RB', 'CAM, LW', 'RWB, RB, RM',
       'CF, CAM, ST', 'RM, CAM, RW', 'RW, ST', 'LW, LM', 'RB, RM, CM',
       'ST, CAM, RW', 'CM, RB, LB', 'CAM, LM, RM', 'RB, RW', 'LM, CM',
       'RM, LM, CM', 'CDM, CM, CB', 'CM, CF', 'CF, LW, RW', 'ST, RM',
       'CAM, CM, CDM', 'LB, CB', 'RW, RWB', 'ST, LM, RM', 'RM, RWB, RB',
       'LM, ST, CAM', 'CAM, ST, CF', 'LW, CM', 'RB, RWB, LB', 'RM, LM',
       'CM, CAM, RM', 'ST, LW, CAM', 'RM, RW, CAM', 'CM, CDM, RM',
       'RB, RM, RWB', 'CDM, CB, LB', 'CAM, ST, LM', 'LM, CM, RM',
       'CF, RW', 'CAM, RM, LW', 'CM, RM, CDM', 'LB, LWB, LM',
       'LW, RW, CF', 'LW, LM, CAM', 'LWB, LW, LB', 'CDM, CM, LM',
       'CB, CM', 'RWB, RW, RB', 'ST, RW, RM', 'LW, RW, CM', 'LM, RM, CAM',
       'LB, RB', 'RWB, RM, RB', 'LM, RB, LB', 'LW, LM, ST', 'ST, RM, LM',
       'CAM, CM, LM', 'CF, CM', 'LW, ST, RW', 'ST, CAM, CF', 'LB, CB, LM',
       'CM, CDM, LM', 'RM, RWB', 'LB, LM, RB', 'RB, LB, CB',
       'CM, CDM, RB', 'LB, CM', 'CF, CAM, LW', 'RM, LWB', 'CF, ST, LM',
       'LB, RB, CB', 'LW, CF, ST', 'RM, ST, CAM', 'LW, RW, ST',
       'ST, LW, LM', 'CM, LW', 'CDM, CM, LB', 'CM, RM, CAM',
       'ST, CF, CAM', 'CM, LM, CAM', 'RWB', 'LM, ST, RM', 'CAM, RM, CM',
       'CAM, LM, CM', 'RW, LW, ST', 'CAM, RM, LM', 'CF, ST, LW',
       'LWB, LB, LM', 'RM, CM, CAM', 'LB, LM, CAM', 'CAM, CDM',
       'RW, RB, RM', 'RM, ST, RW', 'CM, CAM, LW', 'CF, ST, RW',
       'LM, RM, RB', 'LM, RM, CM', 'CB, RB, RM', 'RB, CDM', 'RM, ST, LM',
       'LB, LWB, CB', 'CDM, LB', 'LM, RM, ST', 'RWB, RB, LWB',
       'ST, LM, CAM', 'ST, RM, CAM', 'RB, RWB, RM', 'CF, LM, CAM',
       'CAM, CF, RW', 'RB, RM, LB', 'CDM, RWB', 'CM, RW, CAM',
       'ST, CF, LM', 'RM, LM, RWB', 'RB, LB, RM', 'LM, LW, LB',
       'RM, LM, ST', 'CAM, LM', 'ST, LM, LW', 'LW, RW, RM', 'CF, LW',
       'LB, CM, RB', 'RB, CB, CDM', 'CB, RB, LB', 'CAM, RW, RM',
       'LWB, LM', 'LW, CF, LM', 'CAM, CF, CM', 'LWB, CB', 'CM, CDM, LW',
       'LM, CM, LB', 'CM, RM', 'RW, LW, CF', 'CM, CDM, CB', 'LM, RM, RW',
       'RM, RW, LM', 'RM, CAM, LM', 'LWB, RM, LB', 'RM, LB, RB',
       'CM, CF, RM', 'RM, RB, LB', 'ST, LM, RW', 'CAM, ST, LW',
       'CF, LW, ST', 'LM, LW, CAM', 'RM, RW, CF', 'LW, LM, CF',
       'CM, RW, LW', 'LM, CM, CAM', 'CAM, RW, ST', 'CM, CAM, CF',
       'RW, LWB, LW', 'CB, RB, CDM', 'RW, RM, LW', 'LW, ST, LM',
       'RWB, RW', 'ST, CAM, LM', 'CM, CB', 'RM, RW, CM', 'LWB, CM',
       'RM, LM, LB', 'RM, CAM, ST', 'CDM, RM, RB', 'LM, LB, RB',
       'LB, RB, RWB', 'RM, RWB, CAM', 'CAM, LM, CF', 'LM, CAM, CM',
       'CF, CAM, RW', 'CDM, CM, RM', 'CF, CAM, CM', 'ST, RM, LW',
       'CB, CDM, CM', 'RB, RW, LB', 'ST, RW, CAM', 'CM, LB', 'LW, RM, RW',
       'CM, RM, RW', 'RM, CF, LM', 'CF, LM, RM', 'CAM, ST, RM', 'RW, CF',
       'CM, CAM, ST', 'CAM, CDM, CM', 'RM, RW, LW', 'CAM, LM, LB',
       'CAM, RW, LW', 'CDM, CAM', 'LWB, LM, LB', 'RW, LB', 'LW, CAM, CF',
       'RB, RWB, CB', 'LM, CF, RM', 'RB, LB, RWB', 'RM, LW',
       'CAM, LM, ST', 'LW, LM, LB', 'LB, RB, RM', 'CM, LWB',
       'CDM, RB, RM', 'RM, CM, RB', 'ST, RM, RW', 'LM, RM, LWB',
       'RW, LW, LM', 'LW, CF, RW', 'CM, CDM, LB', 'ST, LM, RB', 'LB, CDM',
       'CM, CB, CDM', 'CB, LB, CDM', 'RW, ST, RM', 'RM, ST, CF',
       'CAM, LW, LM', 'LM, ST, LW', 'CAM, RM, RB', 'RB, CM, RM',
       'CM, LW, LM', 'ST, CAM, RM', 'RW, ST, CAM', 'CM, LB, LM',
       'RB, CDM, RM', 'LM, RWB, RM', 'LM, CAM, LB', 'CAM, LW, RW',
       'CM, RM, RWB', 'RW, CAM, LW', 'RB, CB, LB', 'LB, LM, LW', 'RW, RB',
       'LM, LWB, CM', 'RM, CAM, RB', 'RM, CM, ST', 'RB, RM, LM',
       'LM, LB, LW', 'LM, ST, CF', 'RW, LWB, RM', 'LM, CAM, LW',
       'CB, RWB', 'RM, LW, CAM', 'LB, LW', 'CDM, CM, ST', 'LB, CM, CDM',
       'CF, CAM, LM', 'RW, CAM, RM', 'RW, LM, LW', 'RW, CM, CAM',
       'LM, LW, RW', 'RM, LW, RW', 'LW, LWB, RWB', 'RM, LM, RB',
       'CB, CDM, RB', 'CAM, RW, CM', 'ST, CAM, CM', 'LWB, LM, CM',
       'RW, LW, RWB', 'CB, LB, LWB', 'CM, LM, ST', 'CM, LWB, LM',
       'LB, LW, LM', 'RB, CM, CAM', 'RM, CAM, CF', 'CM, RW',
       'RW, RM, CAM', 'CB, LWB', 'CAM, RB', 'LM, CM, CDM', 'RM, LB, LM',
       'CB, RB, CM', 'RB, CM, RWB', 'LB, RB, LM', 'CAM, ST, RW',
       'LB, LW, RW', 'CDM, CAM, CM', 'CAM, ST, CM', 'LM, CAM, ST',
       'LM, ST, CM', 'CAM, CF, RM', 'CF, ST, RM', 'LM, ST, LB',
       'ST, CAM, LW', 'LWB, CM, LB', 'RWB, RM, LWB', 'LWB, LM, RB',
       'CM, LW, ST', 'LB, LM, CB', 'CM, RM, RB', 'RWB, CB', 'RM, RB, RWB',
       'LB, CM, LM', 'ST, LW, CF', 'RM, RWB, ST', 'CF, ST, CM',
       'LM, LB, LWB', 'LM, RW', 'LM, LWB, LB', 'LB, LWB, RB',
       'RM, RB, LM', 'RM, CM, LM', 'LW, ST, CAM', 'RB, RM, CB',
       'LWB, RWB, LB', 'CF, RM, RW', 'RM, CF, CAM', 'LM, LW, CF',
       'RB, LM, LB', 'CAM, CM, RW', 'LB, CM, LW', 'CM, CF, CAM',
       'RW, RM, ST', 'CDM, RB, CM', 'CM, RB', 'RB, RWB, RW', 'LM, RW, RM',
       'CM, RB, CDM', 'LM, RM, LB', 'CDM, RB, CB', 'RB, CB, RM',
       'RWB, LW, LM', 'ST, CF, RW', 'RM, CM, CDM', 'LM, CF, ST',
       'LW, CAM, LM', 'CDM, LM, CM', 'ST, CM, CAM', 'LM, RM, RWB',
       'CM, CAM, RW', 'CAM, LM, RW', 'LW, LM, RM', 'CAM, RW, CF',
       'LM, ST, RW', 'CB, LWB, LB', 'RW, CF, LW', 'CB, CM, CDM',
       'CB, CAM', 'LW, LB', 'CDM, RB, LB', 'ST, CM, RB', 'RWB, LWB, RB',
       'CM, CB, RB', 'LB, LW, RB', 'CF, RM, RWB', 'LB, RM', 'RM, RW, RB',
       'LB, RM, RB', 'CDM, RM, CM', 'CDM, LB, CM', 'LM, CDM, CM',
       'RW, LM, CAM', 'LM, LB, RM', 'RM, CF, ST', 'RW, CM', 'RM, RWB, LM',
       'CF, CM, ST', 'RW, RM, LM', 'LM, CM, RW', 'RWB, CM', 'RB, RM, CDM',
       'CM, CB, CAM', 'CF, CM, LM', 'RWB, LWB, RM', 'CF, RM',
       'CM, CF, ST', 'RWB, RB, CB', 'LWB, RWB', 'RM, LM, LW',
       'LW, RM, CM', 'LW, CAM, ST', 'ST, RM, RWB', 'ST, CM',
       'CDM, CM, RWB', 'LB, CB, RB', 'CB, ST, CAM', 'CF, RM, CM',
       'CDM, CB, RB', 'CM, LM, RB', 'RB, CB, LWB', 'LM, LB, CDM',
       'LW, LWB', 'RW, CF, CAM', 'RM, RB, CAM', 'LB, RB, CM',
       'RM, CDM, LM', 'LWB, LB, CB', 'LB, RB, CDM', 'RB, CM, LB',
       'CDM, RM', 'LM, RB, CB', 'RW, RWB, RM', 'RM, LW, ST',
       'LB, RB, LWB', 'RM, LM, CDM', 'RB, RM, CAM', 'RM, ST, LW',
       'CF, LM', 'RB, LB, CDM', 'RW, LW, RB', 'RB, RWB, CDM',
       'CM, CAM, LB', 'LW, RW, LWB', 'CB, LWB, RWB', 'LB, CB, CDM',
       'ST, RB, RM', 'CM, RB, RM', 'RW, LM', 'RM, CF, RB', 'CB, RM, RB',
       'RWB, LWB', 'CM, ST, CDM', 'LWB, LW', 'CB, RB, ST', 'LB, LWB, CDM',
       'CB, RWB, RM', 'CB, ST', 'CM, ST', 'LM, LWB, CB', 'ST, LW, LWB',
       'LM, CDM, RM', 'LWB, LB, RW', 'RB, CM, CB', 'LM, RW, ST',
       'CM, RM, LW', 'ST, RW, LM', 'RWB, CM, RM', 'CAM, RWB, CM',
       'CM, RB, LM', 'RM, RB, RW', 'LW, LM, CM', 'RM, LM, LWB',
       'ST, LM, CF', 'LW, RM, CAM', 'RB, RWB, LWB', 'LB, CM, ST',
       'ST, LWB', 'RB, ST, LM', 'CDM, CAM, LM', 'LM, ST, LWB',
       'LB, RB, RW', 'RM, CDM', 'RB, LB, LWB', 'RW, CAM, LM',
       'LB, CDM, LM', 'RW, RB, LM', 'CB, LM', 'RW, LM, RM', 'RM, LB, CM',
       'LW, CAM, RM', 'RW, RB, LB', 'LW, LB, LM', 'CDM, RB, RWB',
       'CB, RW', 'CM, LM, LW', 'LM, RM, CB', 'LM, LWB, ST', 'ST, CB, CDM',
       'LB, CDM, CB', 'CDM, CB, RM', 'RB, RWB, CM', 'ST, RW, CF',
       'ST, CB', 'ST, LW, CM', 'LM, LB, ST', 'ST, CB, RB', 'RB, LM',
       'GK, RB', 'LM, LW, CM', 'LM, CM, LW', 'CB, CAM, CM', 'LM, RB',
       'RWB, CAM', 'RB, CAM', 'CB, CDM, RM', 'ST, RB', 'ST, RWB',
       'CAM, CDM, LM', 'CB, RWB, RB', 'LM, LWB, RM', 'LB, LM, CM',
       'CM, CF, LM', 'CM, RWB', 'CDM, LM', 'ST, CF, RM', 'CAM, LB',
       'RB, RM, ST', 'LM, CDM', 'CDM, RW, RB', 'LM, CF, CAM',
       'LWB, LM, RWB', 'CF, RM, ST', 'CAM, CF, LM', 'RB, ST, CB',
       'RW, RB, LW', 'LB, LM, CDM', 'RB, CB, ST', 'RWB, CB, RB',
       'CDM, ST', 'LW, RM, LM', 'RB, LWB', 'CDM, LB, CB', 'LM, LB, CF',
       'RB, CDM, LB', 'LB, LWB, CM', 'RM, LM, CB', 'CAM, LW, CF',
       'LB, LW, CM', 'RB, CM, CDM', 'LWB, LM, ST', 'CM, RW, RM', 'CB, RM',
       'CM, LM, CB', 'LM, LB, CB', 'ST, RW, CM', 'RM, ST, CM',
       'RWB, RM, LM', 'CM, CAM, RB', 'CM, RWB, CDM', 'LB, LWB, LW'],
      dtype=object)

In [ ]:
#Finding the number of positions
positions = set()
all_positions =fifa_df["Positions"].unique()
for pos in all_positions:
  position = re.findall(pattern=r"\w+", string=pos)
  positions.update(position)

print(f"There are {len(positions)} unique positions")
print(positions)

There are 15 unique positions
{'ST', 'CM', 'LM', 'LWB', 'CDM', 'LB', 'CB', 'RM', 'RWB', 'RB', 'LW', 'CAM', 'CF', 'GK', 'RW'}

In [ ]:
# reordering the positions alphabetically
def reorderPositions(positions: str):
    splitted = re.findall(pattern=r"\w+", string=positions)
    splitted.sort()
    res = " ".join(splitted)
    return res

In [ ]:
fifa_df["Sorted Positions"]= fifa_df["Positions"].apply(reorderPositions)

In [ ]:
fifa_df["Sorted Positions"]

0        CF RW ST
1           LW ST
2              GK
3          CAM CM
4          CAM LW
           ...
18974          CB
18975          CM
18976          CM
18977          RW
18978       CB LB
Name: Sorted Positions, Length: 18979, dtype: object

In [ ]:
fifa_df.drop("Positions", axis=1,inplace=True)

#### 4.8 Cleaning columns with ★ symbols in them

In [ ]:
fifa_df.head()

,ID,Name,Age,↓OVA,POT,Club,Contract_Status,Preferred Foot,BOV,Best Position,...,Hits,Day,Month,Year,Value(€),Wage(€),Release Clause(€),Height(cm),Weight(kg),Sorted Positions
0,158023,L. Messi,33,93,93,FC Barcelona,active,Left,93,RW,...,771,1,7,2004,1035000000,560000,1384000000,170,72,CF RW ST
1,20801,Cristiano Ronaldo,35,92,92,Juventus,active,Right,92,ST,...,562,10,7,2018,630000000,220000,759000000,187,83,LW ST
2,200389,J. Oblak,27,91,93,Atlético Madrid,active,Right,91,GK,...,150,16,7,2014,1200000000,125000,1594000000,188,87,GK
3,192985,K. De Bruyne,29,91,91,Manchester City,active,Right,91,CAM,...,207,30,8,2015,1290000000,370000,1610000000,181,70,CAM CM
4,190871,Neymar Jr,28,91,91,Paris Saint-Germain,active,Right,91,LW,...,595,3,8,2017,1320000000,270000,1665000000,175,68,CAM LW

In [ ]:
fifa_df.columns

Index(['ID', 'Name', 'Age', '↓OVA', 'POT', 'Club', 'Contract_Status',
       'Preferred Foot', 'BOV', 'Best Position', 'Loan Date End', 'Attacking',
       'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility',
       'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina',
       'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions',
       'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W',
       'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits', 'Day', 'Month',
       'Year', 'Value(€)', 'Wage(€)', 'Release Clause(€)', 'Height(cm)',
       'Weight(kg)', 'Sorted Positions'],
      dtype='object')

In [ ]:
fifa_df[["W/F","SM","IR"]]

       W/F  SM   IR
0      4 ★  4★  5 ★
1      4 ★  5★  5 ★
2      3 ★  1★  3 ★
3      5 ★  4★  4 ★
4      5 ★  5★  5 ★
...    ...  ..  ...
18974  2 ★  2★  1 ★
18975  2 ★  2★  1 ★
18976  2 ★  2★  1 ★
18977  3 ★  2★  1 ★
18978  3 ★  2★  1 ★

[18979 rows x 3 columns]

In [ ]:
def removeStars(x):
    x = x.replace("★","")
    return x

In [ ]:
fifa_df[["W/F","SM","IR"]] = fifa_df[["W/F","SM","IR"]].applymap(removeStars)
fifa_df[["W/F","SM","IR"]]

      W/F SM  IR
0      4   4  5
1      4   5  5
2      3   1  3
3      5   4  4
4      5   5  5
...    .. ..  ..
18974  2   2  1
18975  2   2  1
18976  2   2  1
18977  3   2  1
18978  3   2  1

[18979 rows x 3 columns]

### 5. Saving the clean dataset

In [ ]:
import os
os.makedirs('/content/drive/MyDrive/Datasets', exist_ok=True)
fifa_df.to_csv("/content/drive/MyDrive/Datasets/Clean_fifa21_dataset.csv")

## Conclusion

This has been an interesting one. I have managed to clean the dataset and save it for further exploration