<a href="https://colab.research.google.com/github/see-3pO/fifa21-Data-Cleaning-Project/blob/master/fifa21_players_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction


This is a data cleaning and transformation project of fifa21 players dataset sourced from [here](https://www.kaggle.com/datasets/yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring?select=fifa21_raw_data.csv%E2%80%8B).
Some of the guiding questions I followed include:
*   Do the height and weight columns have the appropriate data types?
* Can you separate the joined columns into year, month, and day columns?
* Can you clean and transform the value, wage, and release clause columns into columns of integers?
* How can you remove the newline characters from the Hits column
* Should you separate the Team & Contract Column into separate team and contract columns?

## Code

### 1.  Importing necessary libraries

In [ ]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = '/content'

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

### 2. Creating the dataframe `fifa_df`  to be used

In [ ]:
fifa_df = pd.read_csv('/content/fifa21 raw data v2.csv')
fifa_df
fifa_df.head();

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
fifa_df.tail()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,\n\n\n\nWuhan Zall,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,\n\n\n\nOldham Athletic,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,\n\n\n\nDerry City,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

### 3. Understanding the data

In [ ]:
fifa_df.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [ ]:
fifa_df.shape

(18979, 77)

In [ ]:
fifa_df.isnull().sum()

ID              0
Name            0
LongName        0
photoUrl        0
playerUrl       0
             ...
PAS             0
DRI             0
DEF             0
PHY             0
Hits         2595
Length: 77, dtype: int64

In [ ]:
fifa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  object
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  object
dtypes: int64(54), object(23)
memory usage: 11.1+ MB

In [ ]:
fifa_df.describe()

,ID,Age,↓OVA,POT,BOV,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,...,GK Positioning,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY
count,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,...,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000
mean,226403.384794,25.194109,65.718636,71.136414,66.751726,248.938142,49.688392,45.842405,51.942726,58.768112,...,16.217187,16.519627,1595.286949,355.702197,67.453975,53.457031,57.681016,62.875020,49.866221,64.368934
std,27141.054157,4.710520,6.968999,6.114635,6.747193,74.299428,18.131153,19.567081,17.294409,14.519106,...,17.002239,17.854079,269.874789,40.761117,10.677859,13.827425,10.081857,9.927415,16.443213,9.601883
min,41.000000,16.000000,47.000000,47.000000,48.000000,42.000000,6.000000,3.000000,5.000000,7.000000,...,2.000000,2.000000,747.000000,232.000000,25.000000,16.000000,25.000000,25.000000,12.000000,28.000000
25%,210135.000000,21.000000,61.000000,67.000000,62.000000,222.000000,38.000000,30.000000,44.000000,54.000000,...,8.000000,8.000000,1452.000000,327.000000,61.000000,44.000000,51.000000,57.000000,35.000000,58.000000
50%,232418.000000,25.000000,66.000000,71.000000,67.000000,263.000000,54.000000,49.000000,55.000000,62.000000,...,11.000000,11.000000,1627.000000,356.000000,68.000000,56.000000,58.000000,64.000000,53.000000,65.000000
75%,246922.500000,29.000000,70.000000,75.000000,71.000000,297.000000,63.000000,62.000000,64.000000,68.000000,...,14.000000,14.000000,1781.000000,384.000000,75.000000,64.000000,64.000000,69.000000,63.000000,71.000000
max,259216.000000,53.000000,93.000000,95.000000,93.000000,437.000000,94.000000,95.000000,93.000000,94.000000,...,91.000000,90.000000,2316.000000,498.000000,96.000000,93.000000,93.000000,95.000000,91.000000,91.000000

In [ ]:
#Including only string columns in a DataFrame description.
fifa_df.describe(include=object)

,Name,LongName,photoUrl,playerUrl,Nationality,Club,Contract,Positions,Height,Weight,...,Loan Date End,Value,Wage,Release Clause,W/F,SM,A/W,D/W,IR,Hits
count,18979,18979,18979,18979,18979,18979,18979,18979,18979,18979,...,1013,18979,18979,18979,18979,18979,18979,18979,18979,16384
unique,17920,18852,18979,18979,164,682,131,640,62,79,...,24,255,134,1216,5,5,3,3,5,450
top,J. Rodríguez,Danny Rose,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,England,No Club,2019 ~ 2021,CB,180cm,70kg,...,"Jun 30, 2021",€1.2M,€2K,€0,3 ★,2★,Medium,Medium,1 ★,1
freq,13,3,1,1,1705,237,1706,2441,1474,1495,...,770,582,2899,1261,11695,9142,12701,13956,17629,2325

### 4. Cleaning the Data

#### 4.1 Dropping non-relevant columns

In [ ]:
fifa_df.drop(columns=['photoUrl','playerUrl','LongName','Nationality'], inplace=True)
fifa_df.head()

,ID,Name,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187cm,83kg,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188cm,87kg,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,...,High,Medium,5 ★,91,85,86,94,36,59,595

#### 4.2 Can you separate the joined columns into year, month, and day columns?

In [ ]:
fifa_df['Joined']

0         Jul 1, 2004
1        Jul 10, 2018
2        Jul 16, 2014
3        Aug 30, 2015
4         Aug 3, 2017
             ...
18974    Jul 13, 2018
18975     Aug 1, 2020
18976     Mar 8, 2019
18977    Sep 22, 2020
18978    Jul 29, 2019
Name: Joined, Length: 18979, dtype: object

In [ ]:
fifa_df['Joined'] = fifa_df['Joined'].str.replace(',','')
fifa_df['Joined']

0         Jul 1 2004
1        Jul 10 2018
2        Jul 16 2014
3        Aug 30 2015
4         Aug 3 2017
            ...
18974    Jul 13 2018
18975     Aug 1 2020
18976     Mar 8 2019
18977    Sep 22 2020
18978    Jul 29 2019
Name: Joined, Length: 18979, dtype: object

In [ ]:
fifa_df[['Month', 'Date', 'Year']] = fifa_df['Joined'].str.split(' ', expand=True)
fifa_df[['Month', 'Date', 'Year']]

      Month Date  Year
0       Jul    1  2004
1       Jul   10  2018
2       Jul   16  2014
3       Aug   30  2015
4       Aug    3  2017
...     ...  ...   ...
18974   Jul   13  2018
18975   Aug    1  2020
18976   Mar    8  2019
18977   Sep   22  2020
18978   Jul   29  2019

[18979 rows x 3 columns]

In [ ]:
fifa_df.columns

Index(['ID', 'Name', 'Age', '↓OVA', 'POT', 'Club', 'Contract', 'Positions',
       'Height', 'Weight', 'Preferred Foot', 'BOV', 'Best Position', 'Joined',
       'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Attacking',
       'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility',
       'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina',
       'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions',
       'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W',
       'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits', 'Month', 'Date',
       'Year'],
      dtype='object')

#### 4.3 How can you remove the newline characters from the `Club` column

In [ ]:
fifa_df['Club'] = fifa_df['Club'].str.replace('\n\n\n\n','')
fifa_df.head()

,ID,Name,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,...,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Month,Date,Year
0,158023,L. Messi,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,...,85,92,91,95,38,65,771,Jul,1,2004
1,20801,Cristiano Ronaldo,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187cm,83kg,...,89,93,81,89,35,77,562,Jul,10,2018
2,200389,J. Oblak,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188cm,87kg,...,87,92,78,90,52,90,150,Jul,16,2014
3,192985,K. De Bruyne,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,...,76,86,93,88,64,78,207,Aug,30,2015
4,190871,Neymar Jr,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,...,91,85,86,94,36,59,595,Aug,3,2017

#### 4.4 Can you clean and transform the value, wage, and release clause columns into columns of integers?

In [ ]:
fifa_df.loc[:, ['Value', 'Wage', 'Release Clause']]

         Value   Wage Release Clause
0      €103.5M  €560K        €138.4M
1         €63M  €220K         €75.9M
2        €120M  €125K        €159.4M
3        €129M  €370K          €161M
4        €132M  €270K        €166.5M
...        ...    ...            ...
18974    €100K    €1K           €70K
18975    €130K   €500          €165K
18976    €120K   €500          €131K
18977    €100K    €2K           €88K
18978    €100K    €1K           €79K

[18979 rows x 3 columns]

In [ ]:
fifa_df['Wage'].unique()

array(['€560K', '€220K', '€125K', '€370K', '€270K', '€240K', '€250K',
       '€160K', '€260K', '€210K', '€310K', '€130K', '€350K', '€300K',
       '€190K', '€145K', '€195K', '€100K', '€140K', '€290K', '€82K',
       '€110K', '€230K', '€155K', '€200K', '€165K', '€95K', '€170K',
       '€105K', '€115K', '€150K', '€135K', '€55K', '€58K', '€81K', '€34K',
       '€120K', '€59K', '€90K', '€65K', '€56K', '€71K', '€18K', '€75K',
       '€47K', '€20K', '€84K', '€86K', '€74K', '€78K', '€27K', '€68K',
       '€85K', '€25K', '€46K', '€83K', '€54K', '€79K', '€175K', '€43K',
       '€49K', '€45K', '€38K', '€41K', '€39K', '€23K', '€51K', '€50K',
       '€87K', '€30K', '€14K', '€69K', '€31K', '€64K', '€53K', '€35K',
       '€21K', '€28K', '€17K', '€33K', '€70K', '€32K', '€89K', '€26K',
       '€40K', '€76K', '€72K', '€48K', '€36K', '€29K', '€60K', '€16K',
       '€37K', '€24K', '€52K', '€0', '€62K', '€73K', '€63K', '€19K',
       '€1K', '€66K', '€80K', '€12K', '€2K', '€42K', '€13K', '€900',
       '€57K', '€77K', '€61K', '€22K', '€67K', '€44K', '€15K', '€11K',
       '€8K', '€850', '€10K', '€88K', '€500', '€7K', '€6K', '€9K', '€5K',
       '€700', '€950', '€750', '€3K', '€650', '€600', '€4K', '€800',
       '€550'], dtype=object)

In [ ]:
fifa_df['Value'].unique()

array(['€103.5M', '€63M', '€120M', '€129M', '€132M', '€111M', '€120.5M',
       '€102M', '€185.5M', '€110M', '€113M', '€90.5M', '€82M', '€17.5M',
       '€83.5M', '€33.5M', '€114.5M', '€78M', '€103M', '€109M', '€92M',
       '€10M', '€76.5M', '€89.5M', '€87.5M', '€79.5M', '€124M', '€114M',
       '€95M', '€92.5M', '€105.5M', '€88.5M', '€85M', '€81.5M', '€26M',
       '€21M', '€56M', '€67.5M', '€53M', '€36.5M', '€51M', '€65.5M',
       '€46.5M', '€61.5M', '€72.5M', '€77.5M', '€43.5M', '€32.5M', '€36M',
       '€32M', '€54M', '€49.5M', '€57M', '€66.5M', '€74.5M', '€71.5M',
       '€121M', '€99M', '€67M', '€86.5M', '€93.5M', '€70M', '€62M',
       '€66M', '€58M', '€44M', '€81M', '€37M', '€14.5M', '€46M', '€47.5M',
       '€52.5M', '€54.5M', '€34.5M', '€57.5M', '€51.5M', '€44.5M', '€55M',
       '€48M', '€60.5M', '€63.5M', '€61M', '€29M', '€58.5M', '€55.5M',
       '€42M', '€40.5M', '€43M', '€45.5M', '€34M', '€26.5M', '€42.5M',
       '€35.5M', '€45M', '€41.5M', '€40M', '€11M', '€13.5M', '€29.5M',
       '€27M', '€15.5M', '€38.5M', '€52M', '€33M', '€19M', '€73.5M',
       '€38M', '€35M', '€47M', '€24M', '€30.5M', '€18M', '€28M', '€25.5M',
       '€25M', '€31M', '€23.5M', '€30M', '€31.5M', '€22.5M', '€28.5M',
       '€4M', '€12.5M', '€37.5M', '€27.5M', '€16M', '€15M', '€20.5M',
       '€22M', '€3.4M', '€5M', '€56.5M', '€62.5M', '€0', '€39M', '€24.5M',
       '€21.5M', '€13M', '€8M', '€20M', '€8.5M', '€2.9M', '€9M', '€4.6M',
       '€50M', '€23M', '€18.5M', '€7M', '€19.5M', '€5.5M', '€7.5M',
       '€3.8M', '€14M', '€10.5M', '€16.5M', '€3.6M', '€9.5M', '€39.5M',
       '€17M', '€12M', '€11.5M', '€4.9M', '€3M', '€1.9M', '€6.5M',
       '€1.7M', '€2.4M', '€3.1M', '€6M', '€3.7M', '€4.7M', '€4.3M',
       '€2.1M', '€1.2M', '€1.8M', '€4.8M', '€3.2M', '€1.3M', '€825K',
       '€2.3M', '€1.5M', '€3.9M', '€2.6M', '€3.5M', '€2.8M', '€2.7M',
       '€4.4M', '€4.1M', '€950K', '€1.6M', '€625K', '€1.1M', '€4.5M',
       '€4.2M', '€2.2M', '€3.3M', '€1.4M', '€2M', '€475K', '€925K',
       '€750K', '€725K', '€2.5M', '€1M', '€350K', '€525K', '€600K',
       '€850K', '€800K', '€550K', '€250K', '€400K', '€425K', '€575K',
       '€210K', '€325K', '€900K', '€875K', '€650K', '€700K', '€500K',
       '€975K', '€375K', '€775K', '€275K', '€180K', '€450K', '€675K',
       '€150K', '€240K', '€300K', '€130K', '€220K', '€200K', '€110K',
       '€170K', '€230K', '€90K', '€120K', '€80K', '€190K', '€140K',
       '€160K', '€100K', '€60K', '€50K', '€70K', '€45K', '€35K', '€40K',
       '€25K', '€20K', '€15K', '€30K', '€9K'], dtype=object)

In [ ]:
fifa_df['Release Clause'].unique()

array(['€138.4M', '€75.9M', '€159.4M', ..., '€59K', '€35K', '€64K'],
      dtype=object)

As seen above,columns have the some values in thousands (K) and millions (M) Which have to converted and the currency symbols removed.

In [ ]:
def object_to_float(x):
  if isinstance(x, str):
    #If K is present
    if x.find('K') != -1:
      x = x.replace('K', '').replace('€','')
      return float(x)*1000
     #If M is present
    elif x.find('M') != -1:
      x= x.replace('M','').replace('€','')
      return float(x)*10e6
    elif x.find('€') != -1:
      x = x.replace('€','')
      return float(x)
    else:
      return x
  else:
    return x

In [ ]:
fifa_df['Value(€)'] = fifa_df['Value'].apply(object_to_float)
fifa_df
fifa_df['Value(€)'].unique

<bound method Series.unique of 0        1.035000e+09
1        6.300000e+08
2        1.200000e+09
3        1.290000e+09
4        1.320000e+09
             ...
18974    1.000000e+05
18975    1.300000e+05
18976    1.200000e+05
18977    1.000000e+05
18978    1.000000e+05
Name: Value(€), Length: 18979, dtype: float64>

In [ ]:
fifa_df['Wage(€)'] = fifa_df['Wage'].apply(object_to_float)
fifa_df['Wage(€)'].unique

<bound method Series.unique of 0        560000.0
1        220000.0
2        125000.0
3        370000.0
4        270000.0
           ...
18974      1000.0
18975       500.0
18976       500.0
18977      2000.0
18978      1000.0
Name: Wage(€), Length: 18979, dtype: float64>

In [ ]:
fifa_df['Release Clause(€)'] = fifa_df['Release Clause'].apply(object_to_float)
fifa_df['Release Clause(€)'].unique

<bound method Series.unique of 0        1.384000e+09
1        7.590000e+08
2        1.594000e+09
3        1.610000e+09
4        1.665000e+09
             ...
18974    7.000000e+04
18975    1.650000e+05
18976    1.310000e+05
18977    8.800000e+04
18978    7.900000e+04
Name: Release Clause(€), Length: 18979, dtype: float64>

In [ ]:
fifa_df.columns

Index(['ID', 'Name', 'Age', '↓OVA', 'POT', 'Club', 'Contract', 'Positions',
       'Height', 'Weight', 'Preferred Foot', 'BOV', 'Best Position', 'Joined',
       'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Attacking',
       'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility',
       'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina',
       'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions',
       'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W',
       'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits', 'Month', 'Date',
       'Year', 'Value(€)', 'Wage(€)', 'Release Clause(€)'],
      dtype='object')

In [ ]:
fifa_df.drop(columns=['Value','Wage','Release Clause'], inplace=True)
fifa_df.columns

Index(['ID', 'Name', 'Age', '↓OVA', 'POT', 'Club', 'Contract', 'Positions',
       'Height', 'Weight', 'Preferred Foot', 'BOV', 'Best Position', 'Joined',
       'Loan Date End', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits', 'Month', 'Date', 'Year', 'Value(€)',
       'Wage(€)', 'Release Clause(€)'],
      dtype='object')

In [ ]:
fifa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 76 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 18979 non-null  int64
 1   Name               18979 non-null  object
 2   Age                18979 non-null  int64
 3   ↓OVA               18979 non-null  int64
 4   POT                18979 non-null  int64
 5   Club               18979 non-null  object
 6   Contract           18979 non-null  object
 7   Positions          18979 non-null  object
 8   Height             18979 non-null  object
 9   Weight             18979 non-null  object
 10  Preferred Foot     18979 non-null  object
 11  BOV                18979 non-null  int64
 12  Best Position      18979 non-null  object
 13  Joined             18979 non-null  object
 14  Loan Date End      1013 non-null   object
 15  Attacking          18979 non-null  int64
 16  Crossing           18979 non-null  int64
 17  Finishing          18979 non-null  int64
 18  Heading Accuracy   18979 non-null  int64
 19  Short Passing      18979 non-null  int64
 20  Volleys            18979 non-null  int64
 21  Skill              18979 non-null  int64
 22  Dribbling          18979 non-null  int64
 23  Curve              18979 non-null  int64
 24  FK Accuracy        18979 non-null  int64
 25  Long Passing       18979 non-null  int64
 26  Ball Control       18979 non-null  int64
 27  Movement           18979 non-null  int64
 28  Acceleration       18979 non-null  int64
 29  Sprint Speed       18979 non-null  int64
 30  Agility            18979 non-null  int64
 31  Reactions          18979 non-null  int64
 32  Balance            18979 non-null  int64
 33  Power              18979 non-null  int64
 34  Shot Power         18979 non-null  int64
 35  Jumping            18979 non-null  int64
 36  Stamina            18979 non-null  int64
 37  Strength           18979 non-null  int64
 38  Long Shots         18979 non-null  int64
 39  Mentality          18979 non-null  int64
 40  Aggression         18979 non-null  int64
 41  Interceptions      18979 non-null  int64
 42  Positioning        18979 non-null  int64
 43  Vision             18979 non-null  int64
 44  Penalties          18979 non-null  int64
 45  Composure          18979 non-null  int64
 46  Defending          18979 non-null  int64
 47  Marking            18979 non-null  int64
 48  Standing Tackle    18979 non-null  int64
 49  Sliding Tackle     18979 non-null  int64
 50  Goalkeeping        18979 non-null  int64
 51  GK Diving          18979 non-null  int64
 52  GK Handling        18979 non-null  int64
 53  GK Kicking         18979 non-null  int64
 54  GK Positioning     18979 non-null  int64
 55  GK Reflexes        18979 non-null  int64
 56  Total Stats        18979 non-null  int64
 57  Base Stats         18979 non-null  int64
 58  W/F                18979 non-null  object
 59  SM                 18979 non-null  object
 60  A/W                18979 non-null  object
 61  D/W                18979 non-null  object
 62  IR                 18979 non-null  object
 63  PAC                18979 non-null  int64
 64  SHO                18979 non-null  int64
 65  PAS                18979 non-null  int64
 66  DRI                18979 non-null  int64
 67  DEF                18979 non-null  int64
 68  PHY                18979 non-null  int64
 69  Hits               16384 non-null  object
 70  Month              18979 non-null  object
 71  Date               18979 non-null  object
 72  Year               18979 non-null  object
 73  Value(€)           18979 non-null  float64
 74  Wage(€)            18979 non-null  float64
 75  Release Clause(€)  18979 non-null  float64
dtypes: float64(3), int64(54), object(19)
memory usage: 11.0+ MB

#### 4.5 Should you separate the Team & Contract Column into separate team and contract columns?

In [ ]:
fifa_df['Contract'].unique()

array(['2004  2021', '2018  2022', '2014  2023', '2015  2023',
       '2017  2022', '2017  2023', '2018  2024', '2014  2022',
       '2018  2023', '2016  2023', '2013  2023', '2011  2023',
       '2009  2022', '2005  2021', '2011  2021', '2015  2022',
       '2017  2024', '2010  2024', '2012  2021', '2019  2024',
       '2015  2024', '2017  2025', '2020  2025', '2019  2023',
       '2008  2023', '2015  2021', '2020  2022', '2012  2022',
       '2016  2025', '2013  2022', '2011  2022', '2012  2024',
       '2016  2021', '2012  2023', '2008  2022', '2019  2022',
       '2017  2021', '2013  2024', '2020  2024', '2010  2022',
       '2020  2021', '2011  2024', '2020  2023', '2014  2024',
       '2013  2026', '2016  2022', '2010  2021', '2013  2021',
       '2019  2025', '2018  2025', '2016  2024', '2018  2021',
       '2009  2024', '2007  2022', 'Jun 30, 2021 On Loan', '2009  2021',
       '2019  2021', '2019  2026', 'Free', '2012  2028', '2010  2023',
       '2014  2021', '2015  2025', '2014  2026', '2012  2025',
       '2017  2020', '2002  2022', '2020  2027', '2013  2025',
       'Dec 31, 2020 On Loan', '2019  2020', '2011  2025', '2016  2020',
       '2007  2021', '2020  2026', '2010  2025', '2009  2023',
       '2008  2021', '2020  2020', '2016  2026', 'Jan 30, 2021 On Loan',
       '2012  2020', '2014  2025', 'Jun 30, 2022 On Loan', '2015  2020',
       'May 31, 2021 On Loan', '2018  2020', '2014  2020', '2013  2020',
       '2006  2024', 'Jul 5, 2021 On Loan', 'Dec 31, 2021 On Loan',
       '2004  2025', '2011  2020', 'Jul 1, 2021 On Loan',
       'Jan 1, 2021 On Loan', '2006  2023', 'Aug 31, 2021 On Loan',
       '2006  2021', '2005  2023', '2003  2020', '2009  2020',
       '2002  2020', '2005  2020', '2005  2022', 'Jan 31, 2021 On Loan',
       '2010  2020', 'Dec 30, 2021 On Loan', '2008  2020', '2007  2020',
       '2003  2021', 'Jun 23, 2021 On Loan', 'Jan 3, 2021 On Loan',
       'Nov 27, 2021 On Loan', '2002  2021', 'Jan 17, 2021 On Loan',
       'Jun 30, 2023 On Loan', '1998  2021', '2003  2022', '2007  2023',
       'Jul 31, 2021 On Loan', 'Nov 22, 2020 On Loan',
       'May 31, 2022 On Loan', '2006  2020', 'Dec 30, 2020 On Loan',
       '2007  2025', 'Jan 4, 2021 On Loan', 'Nov 30, 2020 On Loan',
       '2004  2020', '2009  2025', 'Aug 1, 2021 On Loan'], dtype=object)

In [ ]:
fifa_df['Loan Date End'].unique()

array([nan, 'Jun 30, 2021', 'Dec 31, 2020', 'Jan 30, 2021',
       'Jun 30, 2022', 'May 31, 2021', 'Jul 5, 2021', 'Dec 31, 2021',
       'Jul 1, 2021', 'Jan 1, 2021', 'Aug 31, 2021', 'Jan 31, 2021',
       'Dec 30, 2021', 'Jun 23, 2021', 'Jan 3, 2021', 'Nov 27, 2021',
       'Jan 17, 2021', 'Jun 30, 2023', 'Jul 31, 2021', 'Nov 22, 2020',
       'May 31, 2022', 'Dec 30, 2020', 'Jan 4, 2021', 'Nov 30, 2020',
       'Aug 1, 2021'], dtype=object)

In [ ]:
a = fifa_df[fifa_df['Club']=='No Club'].index
for x in a:
  fifa_df['Contract'][x] = ''

AttributeError: 'DataFrame' object has no attribute 'unique'

In [ ]:
fifa_df['Contract'] = fifa_df['Contract'].str.replace('~', '')
fifa_df['Contract']
# fifa_df[['Contract_Start', 'Contract_End']] = fifa_df['Contract'].str.split(' ', expand=True)
# fifa_df[['Contract_Start', 'Contract_End']]

0        2004  2021
1        2018  2022
2        2014  2023
3        2015  2023
4        2017  2022
            ...
18974    2018  2022
18975    2020  2021
18976    2019  2020
18977    2020  2022
18978    2019  2023
Name: Contract, Length: 18979, dtype: object

#### 4.6 How can you make the contract column better?

#### 4.7 Do the height and weight columns have the appropriate data types?

In [ ]:
fifa_df['Height'].dtypes

In [ ]:
fifa_df['Weight'].dtypes

The height and weight columns both have object data types. The Object data type is usually used to store strings and mixed values. This is beacuse the values are save using their units i.e height is saved in cm while weight in kg. These columns don't have the appropriate data types as height and weight are numerical parameters usually represented using float64 or int64 data types.
The columns need to be cleaned.

In [ ]:
fifa_df[['Height','Weight']]

In [ ]:
fifa_df['Height'].unique()

In [ ]:
fifa_df['Weight'].unique()

In [ ]:
# def heightWeightConversion(x):
#   if x.endswith('lbs') == True:
#      x = x.replace("lbs", "")
#      new_x = str(round(int(x)*.453592))
#      return new_x + 'kg'
#   else:
#     x = x.replace("\'", "").replace("\"", "").split()
#      #converting to inches
#     h_in = int(x[0])*12 + int(x[1])
#     #converting to cm
#     h_cm = str(round(h_in*2.54)) + 'cm'
#     return h_cm

In [ ]:
# def convertingHeight(h):
#         h = h.replace("\'", "").replace("\"", "").split()
#         if len(h) == 2:
#             try:
#                 # Convert to inches
#                 h_in = int(h[0]) * 12 + int(h[1])
#                 # Convert to cm
#                 h_cm = str(round(h_in * 2.54)) + 'cm'
#                 return h_cm
#             except ValueError:
#                 return "Invalid input format"
#         elif len(h) == 1 and h[0].isdigit():
#             # Assume input is in centimeters if it's a single numeric value
#             h_cm = str(round(int(h[0]) * 2.54)) + 'cm'
#             return h_cm
#         else:
#             # Handle unexpected input format
#             return "Invalid input format"

In [ ]:
# fifa_df['Height'] = fifa_df['Height'].map(convertingHeight)
# fifa_df['Height'].unique()

In [ ]:
# indexHeight = fifa_df[fifa_df['Height'] == 'Invalid input format'].index
# fifa_df = fifa_df.drop(indexHeight, inplace=True)
# fifa_df['Height'].unique()

In [ ]:
# #converting from lbs to kg
# def convertingWeight(w):
#   if w.endswith('lbs') == True:
#     w = w.replace("lbs", "")
#     new_w = str(round(int(w)*0.453592))
#     return new_w + 'kg'
#   else:
#     return w

In [ ]:
# fifa_df['Weight'] = fifa_df['Weight'].map(convertingWeight)
# fifa_df['Weight'].unique()

### 5. Saving the clean dataset

## Conclusion